export const config = {
  id: "english-listening-capture-demo",
  title: "听力信息捕捉演示器",
  eyebrow: "英语听力 · 抓点流程",
  heroText: "把听力中的场景判断、关键词、数字信息和速记顺序拆成流程图，让孩子先抓点再补细节。",
  heroBadges: ["2 个典型场景", "4 步抓点顺序", "先场景后数字"],
  graphTitle: "听力抓点观察舞台",
  graphNote: "先判断场景和人物关系，再记关键词和数字信息，不要一开始就逐词跟听。",
  controlTitle: "听力样例切换",
  controlHint: "先抓场景，再抓关键点",
  quickGuide: [
    { title: "先说场景", text: "先判断是广播、留言还是通知，不要一开始就逐词跟听。" },
    { title: "再抓关键词", text: "先抓人物、主题和动作，再决定哪些词需要记下来。" },
    { title: "最后记数字", text: "时间、地点、号码和日期，放在最后一层去稳稳补齐。" },
  ],
  sampleTitle: "典型样例",
  sampleHint: "先看校园广播，再看电话留言",
  teachingTitle: "观察提示",
  teachingHint: "每次先说场景类型",
  backHref: "../../modules/unit-english-listening-capture.html",
  backLabel: "返回听力信息捕捉流程图单元",
  controls: [
    {
      key: "sceneId",
      label: "当前样例",
      type: "select",
      default: "campus-radio",
      options: [
        { value: "campus-radio", label: "校园广播" },
        { value: "phone-message", label: "电话留言" },
      ],
    },
    {
      key: "focusNodeId",
      label: "聚焦步骤",
      type: "select",
      default: "keywords",
      options: [
        { value: "scene", label: "场景判断" },
        { value: "keywords", label: "关键词" },
        { value: "numbers", label: "数字信息" },
        { value: "notes", label: "速记结果" },
      ],
    },
  ],
  presets: [
    { id: "radio", label: "校园广播", params: { sceneId: "campus-radio", focusNodeId: "numbers" }, note: "最适合先建立广播类听力要优先抓主题和数字信息的意识。" },
    { id: "phone", label: "电话留言", params: { sceneId: "phone-message", focusNodeId: "keywords" }, note: "帮助孩子看懂留言类听力要先抓谁找谁、为了什么。" },
  ],
  viewport: { xMin: 0, xMax: 12, yMin: 0, yMax: 8 },
  features: { animation: true, gridToggle: false, keyPointToggle: false, explanationCards: true },
  initialMessage: "先让孩子回答：这段听力最像什么场景？",
  liveMessage: "听力先抓场景和关键词，比逐词跟听更稳。",
  resetMessage: "已经回到校园广播样例。",
};
