export const config = {
  id: "parabola-standard-demo",
  title: "抛物线标准方程演示器",
  eyebrow: "圆锥曲线 · 抛物线入门",
  heroText: "把开口方向、焦点、准线和标准方程放在同一张图里，让孩子真正理解 x² = 4ay 或 y² = 4ax 在图上是什么意思。",
  graphTitle: "抛物线变化舞台",
  graphNote: "先看开口方向，再看焦点和准线，最后回头看方程。",
  controlHint: "先换方向，再调 a",
  sampleHint: "四个方向一键切换",
  teachingHint: "焦点和准线一起看",
  backHref: "../../modules/analytic-geometry.html",
  backLabel: "返回解析几何模块",
  controls: [
    {
      key: "direction",
      label: "开口方向",
      type: "select",
      default: "up",
      options: [
        { value: "up", label: "向上" },
        { value: "down", label: "向下" },
        { value: "right", label: "向右" },
        { value: "left", label: "向左" },
      ],
    },
    { key: "a", label: "参数 a", type: "range", min: 0.5, max: 4, step: 0.1, default: 2 },
  ],
  presets: [
    { id: "up-basic", label: "向上开口", params: { direction: "up", a: 2 }, note: "最标准的一种读法：x² = 4ay，焦点在 y 轴正半轴上。" },
    { id: "down-basic", label: "向下开口", params: { direction: "down", a: 2 }, note: "只改符号，开口和焦点就会一起翻到下方。" },
    { id: "right-basic", label: "向右开口", params: { direction: "right", a: 1.5 }, note: "当 y² = 4ax 时，要把“左右开口”和“x 轴是对称轴”对应起来。" },
    { id: "left-wide", label: "向左更开", params: { direction: "left", a: 3 }, note: "a 变大以后，焦点和准线会离顶点更远，图像也会张得更开。" },
  ],
  viewport: { xMin: -10, xMax: 10, yMin: -10, yMax: 10 },
  features: { animation: true, gridToggle: true, keyPointToggle: true, explanationCards: true },
  initialMessage: "准备好了，先切换开口方向，再盯焦点和准线的位置变化。",
  liveMessage: "抛物线最容易混的不是公式本身，而是谁平方、往哪开、焦点在哪。",
  resetMessage: "已经回到最基础的向上开口抛物线。",
};
