export const config = {
  id: "physics-accelerated-motion-demo",
  title: "匀变速直线运动演示器",
  eyebrow: "物理运动学 · 匀变速直线运动",
  heroText: "把初速度、加速度、速度图像和位移累计放到一起，看清匀变速运动为什么不是“多背一个公式”。",
  graphTitle: "速度-时间图像",
  graphNote: "横轴是时间 t，纵轴是速度 v。紫色阴影提示从 0 到当前时刻的位移累计。",
  controlHint: "推荐按 a → v0 → t 的顺序观察",
  sampleHint: "先看 4 种典型变化方式",
  teachingHint: "先说出斜率和面积代表什么",
  backHref: "../../modules/unit-physics-accelerated-motion.html",
  backLabel: "返回匀变速直线运动单元",
  controls: [
    { key: "v0", label: "初速度 v0", type: "range", min: -4, max: 6, step: 0.2, default: 1 },
    { key: "a", label: "加速度 a", type: "range", min: -2, max: 3, step: 0.1, default: 2 },
    { key: "t", label: "观察时刻 t", type: "range", min: 0, max: 8, step: 0.2, default: 3 },
  ],
  presets: [
    { id: "speed-up", label: "持续加速", params: { v0: 1, a: 2, t: 3 }, note: "加速度为正，v-t 图像向右上倾斜，速度会稳定增大。" },
    { id: "slow-down", label: "持续减速", params: { v0: 5, a: -1.2, t: 3 }, note: "加速度为负，速度会稳定减小，但仍可能还没减到 0。" },
    { id: "from-rest", label: "静止起步", params: { v0: 0, a: 1.5, t: 4 }, note: "从静止出发时，图像从原点起步，面积就是这段时间里的位移累计。" },
    { id: "reverse-risk", label: "可能反向", params: { v0: 2, a: -1.5, t: 4 }, note: "速度减到 0 后如果继续变化，运动方向就可能反过来。" },
  ],
  viewport: { xMin: 0, xMax: 8, yMin: -8, yMax: 8 },
  features: { animation: true, gridToggle: true, keyPointToggle: true, explanationCards: true },
  initialMessage: "准备好了，先固定一个时刻，只改加速度 a，看 v-t 图像斜率怎样变化。",
  liveMessage: "匀变速里最值得先盯住两件事：斜率看加速度，面积看位移累计。",
  resetMessage: "已经回到最基础的匀变速运动模型。",
};
