export const config = {
  id: "chemistry-lab-device-demo",
  title: "实验装置演示器",
  eyebrow: "化学实验与现象 · 实验装置",
  heroText: "把装置分工、步骤顺序和风险提示放到同一条流程里，让孩子看到“为什么这一步必须排在前面”。",
  graphTitle: "实验装置与步骤流程",
  graphNote: "每个节点表示一步操作或一个装置职责，箭头表示顺序，底部风险提示帮助孩子把失误与结果对应起来。",
  controlTitle: "实验场景",
  controlHint: "先认装置职责，再看顺序",
  sampleTitle: "典型样例",
  sampleHint: "先看气体制备，再看过滤和滴定",
  teachingTitle: "观察提示",
  teachingHint: "装置图一定要和步骤链一起看",
  backHref: "../../modules/unit-chemistry-lab-devices.html",
  backLabel: "返回实验装置单元",
  controls: [
    {
      key: "sceneId",
      label: "当前场景",
      type: "select",
      default: "gas-preparation",
      options: [
        { value: "gas-preparation", label: "气体制备" },
        { value: "filtration", label: "过滤操作" },
        { value: "titration", label: "滴定流程" },
      ],
    },
    {
      key: "strictMode",
      label: "显示风险提醒",
      type: "toggle",
      default: true,
    },
  ],
  presets: [
    { id: "gas", label: "气体制备", params: { sceneId: "gas-preparation", strictMode: true }, note: "最适合讲“先检漏再加药品”的顺序意识。" },
    { id: "filtration", label: "过滤操作", params: { sceneId: "filtration", strictMode: true }, note: "过滤看似简单，但很适合训练步骤与细节意识。" },
    { id: "titration", label: "滴定流程", params: { sceneId: "titration", strictMode: true }, note: "把装置职责和误差来源放在一起，实验题会更好讲。" },
  ],
  viewport: { xMin: 0, xMax: 12, yMin: 0, yMax: 8 },
  features: { animation: true, gridToggle: false, keyPointToggle: false, explanationCards: true },
  initialMessage: "先让孩子说顺序，再让他解释为什么这个顺序不能乱。",
  liveMessage: "实验装置不是孤立图片，必须和步骤链、风险点一起看。",
  resetMessage: "已经回到气体制备的基础场景。",
};
