export const config = {
  id: "transform-demo",
  title: "函数变换演示器",
  eyebrow: "函数主线 · 平移与伸缩",
  heroText: "把上下平移、左右平移和伸缩变化放到一张图里统一理解。",
  graphTitle: "函数变换舞台",
  graphNote: "先看底函数，再看平移，最后看伸缩。",
  controlHint: "按 底函数 → 平移 → 伸缩 的顺序看",
  sampleHint: "常见变换一键切换",
  teachingHint: "不要把左右和上下搞反",
  controls: [
    {
      key: "baseType",
      label: "底函数",
      type: "select",
      default: "quadratic",
      options: [
        { value: "quadratic", label: "x²" },
        { value: "absolute", label: "|x|" },
        { value: "sine", label: "sin(x)" },
      ],
    },
    { key: "horizontalShift", label: "左右平移", type: "range", min: -4, max: 4, step: 0.2, default: 0 },
    { key: "verticalShift", label: "上下平移", type: "range", min: -4, max: 4, step: 0.2, default: 0 },
    { key: "horizontalScale", label: "横向伸缩", type: "range", min: 0.5, max: 2.5, step: 0.1, default: 1 },
    { key: "verticalScale", label: "纵向伸缩", type: "range", min: -2.5, max: 2.5, step: 0.1, default: 1 },
  ],
  presets: [
    { id: "standard", label: "标准函数", params: { baseType: "quadratic", horizontalShift: 0, verticalShift: 0, horizontalScale: 1, verticalScale: 1 }, note: "先看原函数，再做任何变换。" },
    { id: "right", label: "向右平移", params: { baseType: "quadratic", horizontalShift: 2, verticalShift: 0, horizontalScale: 1, verticalScale: 1 }, note: "左右平移最容易和括号里的正负号搞反。" },
    { id: "up", label: "整体上移", params: { baseType: "absolute", horizontalShift: 0, verticalShift: 2, horizontalScale: 1, verticalScale: 1 }, note: "函数外面加数，图像整体上下移动。" },
    { id: "stretch", label: "纵向拉伸", params: { baseType: "sine", horizontalShift: 0, verticalShift: 0, horizontalScale: 1, verticalScale: 2 }, note: "乘在函数外面的系数，优先理解成纵向伸缩。" },
  ],
  viewport: { xMin: -8, xMax: 8, yMin: -6, yMax: 8 },
  features: { animation: true, gridToggle: true, keyPointToggle: true, explanationCards: true },
  initialMessage: "先切换底函数，再观察平移和伸缩，顺序不要乱。",
  liveMessage: "函数变换最容易混的，是左右平移和横向伸缩。",
  resetMessage: "已经回到最基础的标准函数。",
};
