export const config = {
  id: "physics-overweight-demo",
  title: "超重与失重演示器",
  eyebrow: "物理受力分析 · 超重与失重",
  heroText: "把支持力、重力、加速度方向和电梯情境放到同一张受力图里，让孩子看懂“感觉变重变轻”背后真正变化的量。",
  graphTitle: "电梯情境受力图",
  graphNote: "红色表示重力，绿色表示支持力，蓝色表示加速度方向。关键不是重力变没变，而是支持力怎样变化。",
  controlHint: "推荐按 加速度 → 质量 → 重力加速度 的顺序观察",
  sampleHint: "先看 4 种典型电梯状态",
  teachingHint: "先判断支持力比重力大、等于还是小于",
  backHref: "../../modules/unit-physics-overweight-weightlessness.html",
  backLabel: "返回超重与失重单元",
  controls: [
    { key: "m", label: "质量 m", type: "range", min: 30, max: 90, step: 1, default: 50 },
    { key: "g", label: "重力加速度 g", type: "range", min: 8, max: 12, step: 0.1, default: 10 },
    { key: "a", label: "电梯加速度 a", type: "range", min: -10, max: 6, step: 0.2, default: 0 },
  ],
  presets: [
    { id: "normal", label: "正常状态", params: { m: 50, g: 10, a: 0 }, note: "没有额外加速度时，支持力和重力平衡，称重读数就是平时的重量。" },
    { id: "overweight", label: "超重", params: { m: 50, g: 10, a: 2 }, note: "电梯向上加速时，支持力必须比重力更大，所以人会感觉更重。" },
    { id: "underweight", label: "失重", params: { m: 50, g: 10, a: -4 }, note: "电梯向下加速时，支持力会减小，所以会感觉变轻。" },
    { id: "free-fall", label: "完全失重", params: { m: 50, g: 10, a: -10 }, note: "自由落体时支持力降到 0，体感上会完全失重。" },
  ],
  viewport: { xMin: 0, xMax: 10, yMin: 0, yMax: 10 },
  features: { animation: true, gridToggle: false, keyPointToggle: true, explanationCards: true },
  initialMessage: "准备好了，先只改电梯加速度，看支持力是怎么跟着变的。",
  liveMessage: "超重与失重里真正变化的不是重力，而是支持力。",
  resetMessage: "已经回到最基础的正常状态。",
};
