export const config = {
  id: "physics-free-fall-demo",
  title: "自由落体演示器",
  eyebrow: "物理运动学 · 自由落体",
  heroText: "把重力加速度、速度变化、下落位移和剩余高度放到一起，让孩子把自由落体重新看成一个连续变化过程。",
  graphTitle: "自由落体速度-时间图像",
  graphNote: "横轴是时间 t，纵轴是向下速度 v。绿色面积提示从 0 到当前时刻已经积累的下落位移。",
  controlHint: "推荐按 重力加速度 → 初始高度 → 观察时刻 的顺序观察",
  sampleHint: "先看 4 种典型自由落体情境",
  teachingHint: "先说出速度怎么变，再看高度怎样减少",
  backHref: "../../modules/unit-physics-free-fall.html",
  backLabel: "返回自由落体单元",
  controls: [
    { key: "g", label: "重力加速度 g", type: "range", min: 6, max: 12, step: 0.1, default: 9.8 },
    { key: "h0", label: "初始高度 h0", type: "range", min: 20, max: 120, step: 1, default: 80 },
    { key: "t", label: "观察时刻 t", type: "range", min: 0, max: 6, step: 0.1, default: 2 },
  ],
  presets: [
    { id: "standard", label: "标准重力场", params: { g: 9.8, h0: 80, t: 2 }, note: "最基础的自由落体模型，速度按固定快慢增大，面积表示已下落位移。" },
    { id: "high-start", label: "高处下落", params: { g: 9.8, h0: 120, t: 3 }, note: "初始高度更高时，孩子更容易观察“速度越来越快，但还没落地”的过程。" },
    { id: "low-start", label: "低处观察", params: { g: 9.8, h0: 30, t: 2 }, note: "初始高度较低时，更适合讨论何时接近地面，以及物理模型和真实情境怎样对应。" },
    { id: "planet-compare", label: "重力变化对比", params: { g: 7.5, h0: 80, t: 2.5 }, note: "降低 g 后，v-t 图像斜率会变缓，也就是速度增加得没那么快。" },
  ],
  viewport: { xMin: 0, xMax: 6, yMin: 0, yMax: 30 },
  features: { animation: true, gridToggle: true, keyPointToggle: true, explanationCards: true },
  initialMessage: "准备好了，先固定一个时刻，只改重力加速度 g，看 v-t 图像斜率怎样变化。",
  liveMessage: "自由落体里最值得先盯住的是：斜率看重力加速度，面积看下落位移。",
  resetMessage: "已经回到最基础的自由落体模型。",
};
