export const config = {
  id: "physics-uniform-chase-demo",
  title: "两车匀速追及演示器",
  eyebrow: "物理运动学 · 两车匀速追及",
  heroText: "把前车、后车、起步位置差和速度差放到同一张 s-t 图像里，让孩子直接看到什么时候追上、为什么追上。",
  graphTitle: "双车位移-时间图像",
  graphNote: "蓝线表示前车，绿线表示后车。两条线相交，表示同一时刻位置相同，也就是现实中的追上。",
  controlHint: "推荐按 后车速度 → 前车速度 → 两车起点 → 观察时刻 的顺序观察",
  sampleHint: "先看 4 种典型追及情境",
  teachingHint: "先说出能不能追上，再回头解释为什么",
  backHref: "../../modules/unit-physics-uniform-chase.html",
  backLabel: "返回两车匀速追及单元",
  controls: [
    { key: "leadStart", label: "前车起点 sA0", type: "range", min: 2, max: 12, step: 0.5, default: 6 },
    { key: "leadSpeed", label: "前车速度 vA", type: "range", min: 0.5, max: 4, step: 0.1, default: 1.5 },
    { key: "chaseStart", label: "后车起点 sB0", type: "range", min: -4, max: 6, step: 0.5, default: 0 },
    { key: "chaseSpeed", label: "后车速度 vB", type: "range", min: 0.5, max: 5, step: 0.1, default: 3 },
    { key: "t", label: "观察时刻 t", type: "range", min: 0, max: 10, step: 0.2, default: 2 },
  ],
  presets: [
    { id: "catch-up", label: "稳定追上", params: { leadStart: 6, leadSpeed: 1.5, chaseStart: 0, chaseSpeed: 3, t: 2 }, note: "后车更快，所以两条直线会相交，说明存在追上时刻。" },
    { id: "far-but-fast", label: "起点差大但能追上", params: { leadStart: 10, leadSpeed: 1.2, chaseStart: 0, chaseSpeed: 3.5, t: 3 }, note: "虽然起点差更大，但只要速度差足够明显，后车仍然可以追上。" },
    { id: "cannot-catch", label: "追不上", params: { leadStart: 6, leadSpeed: 2, chaseStart: 0, chaseSpeed: 2, t: 4 }, note: "两车速度相同，间距始终不变，所以不会追上。" },
    { id: "late-start", label: "后车起点更靠后", params: { leadStart: 8, leadSpeed: 1.8, chaseStart: -2, chaseSpeed: 4, t: 2.5 }, note: "后车起步更靠后，但只要更快，仍然会在未来某个时刻追上。" },
  ],
  viewport: { xMin: 0, xMax: 10, yMin: -4, yMax: 18 },
  features: { animation: true, gridToggle: true, keyPointToggle: true, explanationCards: true },
  initialMessage: "准备好了，先固定起点差，只改后车速度，看两条线会不会相交。",
  liveMessage: "追及里最关键的不是单看谁快，而是要一起看起点差和速度差。",
  resetMessage: "已经回到最基础的匀速追及模型。",
};
