export const config = {
  id: "physics-work-energy-synthesis-demo",
  title: "功能量综合应用演示器",
  eyebrow: "物理功与能量 · 综合应用",
  heroText: "把外力做功、摩擦损失、初动能和末动能放到同一张能量对照图里，让孩子更容易判断综合题该优先用哪一种能量方法。",
  graphTitle: "功能量综合对照图",
  graphNote: "蓝条表示外力做功，红条表示摩擦损失，紫条是初动能，绿条是末动能。关键观察点是净功怎样推动动能变化。",
  controlHint: "推荐按 外力做功 → 摩擦损失 → 初动能 的顺序观察",
  sampleHint: "先看 4 种典型综合场景",
  teachingHint: "先判断有没有耗散，再决定优先用哪种方法",
  backHref: "../../modules/unit-physics-work-energy-synthesis.html",
  backLabel: "返回功能量综合应用单元",
  controls: [
    { key: "workByForce", label: "外力做功 W外", type: "range", min: 0, max: 200, step: 5, default: 120 },
    { key: "frictionLoss", label: "摩擦损失 W损", type: "range", min: 0, max: 120, step: 5, default: 30 },
    { key: "initialKinetic", label: "初动能 Ek0", type: "range", min: 0, max: 120, step: 5, default: 20 },
  ],
  presets: [
    { id: "with-loss", label: "有摩擦损失", params: { workByForce: 120, frictionLoss: 30, initialKinetic: 20 }, note: "存在明显损失时，优先看净功和动能变化，通常会比硬套机械能守恒更稳。" },
    { id: "no-loss", label: "无损耗理想态", params: { workByForce: 80, frictionLoss: 0, initialKinetic: 20 }, note: "没有额外耗散时，机械能视角会更顺，这时就不必先纠结损失项。" },
    { id: "large-loss", label: "损失较大", params: { workByForce: 150, frictionLoss: 70, initialKinetic: 15 }, note: "损失越明显，越要先把损失单独拎出来看，再回到动能变化。" },
    { id: "high-start", label: "初动能较大", params: { workByForce: 60, frictionLoss: 20, initialKinetic: 80 }, note: "初始本来就有较大动能时，外力做功只是继续在原有基础上推动变化。" },
  ],
  viewport: { xMin: -0.5, xMax: 9.5, yMin: -0.12, yMax: 1.28 },
  features: { animation: true, gridToggle: false, keyPointToggle: true, explanationCards: true },
  initialMessage: "准备好了，先只改摩擦损失，看推荐方法会不会从机械能转回动能定理。",
  liveMessage: "功能量综合题里，先判断有没有明显耗散，通常就能决定优先用哪条思路。",
  resetMessage: "已经回到最基础的功能量综合场景。",
};
