export const config = {
  id: "sequence-basic-demo",
  title: "等差与等比数列生成演示器",
  eyebrow: "数列主线 · 等差与等比",
  heroText: "把“每次加同样多”和“每次乘同样倍数”放在一起，看出线性增长和指数增长的根本差别。",
  graphTitle: "逐项生成对比",
  graphNote: "绿线表示等差数列，橙线表示等比数列。每个点都代表第 n 项。",
  controlHint: "推荐按 a1 → d → q → n 的顺序观察",
  sampleHint: "先把 4 种典型差别看熟",
  teachingHint: "先说出差别，再回头看图",
  controls: [
    { key: "a1", label: "首项 a1", type: "range", min: 1, max: 6, step: 0.5, default: 2 },
    { key: "d", label: "公差 d", type: "range", min: -3, max: 4, step: 0.5, default: 2 },
    { key: "q", label: "公比 q", type: "range", min: 0.5, max: 2.2, step: 0.1, default: 1.5 },
    { key: "count", label: "项数 n", type: "range", min: 5, max: 10, step: 1, default: 8 },
  ],
  presets: [
    { id: "steady-rise", label: "稳步增加", params: { a1: 2, d: 2, q: 1.2, count: 8 }, note: "先看等差数列稳定增加，再看等比数列前期可能没那么明显。" },
    { id: "double-gap", label: "倍增拉开", params: { a1: 2, d: 2, q: 2, count: 8 }, note: "当公比大于 1 且比较大时，后面几项会很快拉开差距。" },
    { id: "geo-decay", label: "等比衰减", params: { a1: 4, d: 1, q: 0.6, count: 8 }, note: "当 0 < q < 1 时，等比数列会逐项变小，但等差数列还会继续线性增长。" },
    { id: "arith-fall", label: "等差递减", params: { a1: 8, d: -1, q: 1.3, count: 8 }, note: "公差为负时，等差数列会线性下降；等比数列仍可能继续增长。" },
  ],
  viewport: { xMin: 0, xMax: 10, yMin: -10, yMax: 20 },
  features: { animation: true, gridToggle: true, keyPointToggle: true, explanationCards: true },
  initialMessage: "准备好了，先固定首项和项数，只看 d 与 q 的变化。",
  liveMessage: "看数列时，最稳的抓手不是公式本身，而是“固定差”和“固定倍”的变化方式。",
  resetMessage: "已经回到最基础的数列对比模型。",
};
