export const config = {
  id: "solid-rotation-demo",
  title: "旋转体生成演示器",
  eyebrow: "立体几何 · 旋转生成",
  heroText: "把平面图形绕轴旋转生成立体的过程直接摆出来，帮助孩子把“长方形变圆柱、三角形变圆锥、半圆变球”看成直觉。",
  graphTitle: "旋转体生成舞台",
  graphNote: "左边看平面图形和旋转轴，右边看旋转后得到的立体示意。",
  controlHint: "先换平面图形，再看半径和高度",
  sampleHint: "先熟悉圆柱、圆锥、球三类最常见旋转体",
  teachingHint: "先看谁绕谁转",
  controls: [
    {
      key: "profileType",
      label: "平面图形",
      type: "select",
      default: "rectangle",
      options: [
        { value: "rectangle", label: "长方形" },
        { value: "triangle", label: "直角三角形" },
        { value: "semicircle", label: "半圆" },
      ],
    },
    { key: "radius", label: "半径 r", type: "range", min: 2, max: 6, step: 0.2, default: 4 },
    { key: "height", label: "高 h", type: "range", min: 3, max: 8, step: 0.2, default: 6 },
  ],
  presets: [
    { id: "cylinder", label: "长方形→圆柱", params: { profileType: "rectangle", radius: 4, height: 6 }, note: "长方形绕一条边旋转，可以得到圆柱。" },
    { id: "cone", label: "三角形→圆锥", params: { profileType: "triangle", radius: 4, height: 6 }, note: "直角三角形绕一条直角边旋转，可以得到圆锥。" },
    { id: "sphere", label: "半圆→球", params: { profileType: "semicircle", radius: 4, height: 0 }, note: "半圆绕直径旋转，会形成球。" },
  ],
  viewport: { xMin: 0, xMax: 100, yMin: 0, yMax: 100 },
  features: { animation: true, gridToggle: false, keyPointToggle: false, explanationCards: true },
  initialMessage: "准备好了，先切换平面图形，看它绕轴后会生成什么立体。",
  liveMessage: "旋转体最关键的是先看：哪一个平面图形，在绕哪一条轴转。",
  resetMessage: "已经回到最基础的旋转体模型。",
};
