export const config = {
  id: "chemistry-mole-demo",
  title: "物质的量演示器",
  eyebrow: "化学语言与定量基础 · 物质的量",
  heroText: "把物质的量 n 放回中央枢纽位置，让孩子同时看到质量、微粒数和气体体积为什么都要先经过它。",
  graphTitle: "定量换算关系网",
  graphNote: "中间是物质的量，三条箭头分别连接质量、微粒数和气体体积。拖动参数时，先盯住 n 怎样统领全局。",
  controlTitle: "参数控制",
  controlHint: "先固定 n，再改常量",
  sampleTitle: "典型样例",
  sampleHint: "先看水，再看气体，再看微粒数放大",
  teachingTitle: "观察提示",
  teachingHint: "始终把 n 放在中间",
  backHref: "../../modules/unit-chemistry-mole.html",
  backLabel: "返回物质的量单元",
  controls: [
    { key: "amount", label: "物质的量 n", type: "range", min: 0.5, max: 5, step: 0.1, default: 2 },
    { key: "molarMass", label: "摩尔质量 M", type: "range", min: 2, max: 98, step: 1, default: 18 },
    { key: "gasMolarVolume", label: "气体摩尔体积 Vm", type: "range", min: 22.4, max: 24.5, step: 0.1, default: 22.4 },
  ],
  presets: [
    { id: "water", label: "水分子视角", params: { amount: 2, molarMass: 18, gasMolarVolume: 22.4 }, note: "最适合先建立 m = nM 这一条最熟悉的桥。" },
    { id: "oxygen-gas", label: "氧气体积", params: { amount: 1.5, molarMass: 32, gasMolarVolume: 22.4 }, note: "讲气体时，把体积换算也重新拉回 n，会比单独背公式稳很多。" },
    { id: "classroom-gas", label: "常温近似", params: { amount: 2, molarMass: 44, gasMolarVolume: 24 }, note: "提醒孩子气体体积换算要结合题目条件，不要默认任何场景都用 22.4。" },
  ],
  viewport: { xMin: 0, xMax: 12, yMin: 0, yMax: 8 },
  features: { animation: true, gridToggle: false, keyPointToggle: false, explanationCards: true },
  initialMessage: "先让孩子只回答一个问题：为什么质量、微粒数、气体体积都要先经过 n？",
  liveMessage: "只要中央的 n 不乱，三条换算链就不会散。",
  resetMessage: "已经回到最基础的物质的量换算场景。",
};
