export type MigrationPriority = "high" | "medium" | "low";
export type MigrationStatus = "planned" | "migrating" | "migrated" | "merged" | "archived";
export type MigrationAction =
  | "migrate-as-is"
  | "merge"
  | "split"
  | "rewrite-demo"
  | "content-only"
  | "archive-only";

export type MigrationManifestRecord = {
  legacyType: "module" | "unit" | "demo";
  legacyPath: string;
  legacyTitle: string;
  targetSubject: "math" | "physics" | "chemistry" | "english";
  targetModule: string;
  targetUnitSlug: string | null;
  action: MigrationAction;
  status: MigrationStatus;
  priority: MigrationPriority;
  notes: string;
};

export const migrationManifest: MigrationManifestRecord[] = [
  {
    "legacyType": "module",
    "legacyPath": "legacy/prototype-v1/modules/chemistry-language.html",
    "legacyTitle": "化学语言与定量基础",
    "targetSubject": "chemistry",
    "targetModule": "chemical-language",
    "targetUnitSlug": null,
    "action": "migrate-as-is",
    "status": "planned",
    "priority": "high",
    "notes": "保留模块主线，迁入新站正式模块页。"
  },
  {
    "legacyType": "demo",
    "legacyPath": "legacy/prototype-v1/demos/分散系与胶体演示器",
    "legacyTitle": "分散系与胶体演示器",
    "targetSubject": "chemistry",
    "targetModule": "chemical-language",
    "targetUnitSlug": "chemistry-dispersion-colloid",
    "action": "rewrite-demo",
    "status": "planned",
    "priority": "medium",
    "notes": "旧演示器重写为正式 DemoDefinition，目标单元：分散系与胶体。"
  },
  {
    "legacyType": "unit",
    "legacyPath": "legacy/prototype-v1/modules/unit-chemistry-dispersion-colloid.html",
    "legacyTitle": "分散系与胶体",
    "targetSubject": "chemistry",
    "targetModule": "chemical-language",
    "targetUnitSlug": "chemistry-dispersion-colloid",
    "action": "migrate-as-is",
    "status": "planned",
    "priority": "medium",
    "notes": "迁入正式知识点页，并按价值补交互 demo。"
  },
  {
    "legacyType": "demo",
    "legacyPath": "legacy/prototype-v1/demos/物质分类演示器",
    "legacyTitle": "物质分类演示器",
    "targetSubject": "chemistry",
    "targetModule": "chemical-language",
    "targetUnitSlug": "chemistry-material-classification",
    "action": "rewrite-demo",
    "status": "planned",
    "priority": "high",
    "notes": "旧演示器重写为正式 DemoDefinition，目标单元：物质分类与转化关系。"
  },
  {
    "legacyType": "unit",
    "legacyPath": "legacy/prototype-v1/modules/unit-chemistry-material-classification.html",
    "legacyTitle": "物质分类与转化关系",
    "targetSubject": "chemistry",
    "targetModule": "chemical-language",
    "targetUnitSlug": "chemistry-material-classification",
    "action": "migrate-as-is",
    "status": "planned",
    "priority": "high",
    "notes": "迁入正式知识点页，并按价值补交互 demo。"
  },
  {
    "legacyType": "demo",
    "legacyPath": "legacy/prototype-v1/demos/物质的量演示器",
    "legacyTitle": "物质的量演示器",
    "targetSubject": "chemistry",
    "targetModule": "chemical-language",
    "targetUnitSlug": "chemistry-mole",
    "action": "rewrite-demo",
    "status": "planned",
    "priority": "high",
    "notes": "旧演示器重写为正式 DemoDefinition，目标单元：物质的量与微粒关系。"
  },
  {
    "legacyType": "unit",
    "legacyPath": "legacy/prototype-v1/modules/unit-chemistry-mole.html",
    "legacyTitle": "物质的量与微粒关系",
    "targetSubject": "chemistry",
    "targetModule": "chemical-language",
    "targetUnitSlug": "chemistry-mole",
    "action": "migrate-as-is",
    "status": "planned",
    "priority": "high",
    "notes": "迁入正式知识点页，并按价值补交互 demo。"
  },
  {
    "legacyType": "module",
    "legacyPath": "legacy/prototype-v1/modules/chemistry-elements.html",
    "legacyTitle": "元素化合物",
    "targetSubject": "chemistry",
    "targetModule": "elements-compounds",
    "targetUnitSlug": null,
    "action": "migrate-as-is",
    "status": "planned",
    "priority": "high",
    "notes": "保留模块主线，迁入新站正式模块页。"
  },
  {
    "legacyType": "demo",
    "legacyPath": "legacy/prototype-v1/demos/氯及其化合物演示器",
    "legacyTitle": "氯及其化合物演示器",
    "targetSubject": "chemistry",
    "targetModule": "elements-compounds",
    "targetUnitSlug": "chemistry-chlorine",
    "action": "rewrite-demo",
    "status": "planned",
    "priority": "medium",
    "notes": "旧演示器重写为正式 DemoDefinition，目标单元：氯及其化合物。"
  },
  {
    "legacyType": "unit",
    "legacyPath": "legacy/prototype-v1/modules/unit-chemistry-chlorine.html",
    "legacyTitle": "氯及其化合物",
    "targetSubject": "chemistry",
    "targetModule": "elements-compounds",
    "targetUnitSlug": "chemistry-chlorine",
    "action": "migrate-as-is",
    "status": "planned",
    "priority": "medium",
    "notes": "迁入正式知识点页，并按价值补交互 demo。"
  },
  {
    "legacyType": "demo",
    "legacyPath": "legacy/prototype-v1/demos/铁及其化合物演示器",
    "legacyTitle": "铁及其化合物演示器",
    "targetSubject": "chemistry",
    "targetModule": "elements-compounds",
    "targetUnitSlug": "chemistry-iron",
    "action": "rewrite-demo",
    "status": "planned",
    "priority": "medium",
    "notes": "旧演示器重写为正式 DemoDefinition，目标单元：铁及其化合物。"
  },
  {
    "legacyType": "unit",
    "legacyPath": "legacy/prototype-v1/modules/unit-chemistry-iron.html",
    "legacyTitle": "铁及其化合物",
    "targetSubject": "chemistry",
    "targetModule": "elements-compounds",
    "targetUnitSlug": "chemistry-iron",
    "action": "migrate-as-is",
    "status": "planned",
    "priority": "medium",
    "notes": "迁入正式知识点页，并按价值补交互 demo。"
  },
  {
    "legacyType": "demo",
    "legacyPath": "legacy/prototype-v1/demos/钠及其化合物演示器",
    "legacyTitle": "钠及其化合物演示器",
    "targetSubject": "chemistry",
    "targetModule": "elements-compounds",
    "targetUnitSlug": "chemistry-sodium",
    "action": "rewrite-demo",
    "status": "planned",
    "priority": "medium",
    "notes": "旧演示器重写为正式 DemoDefinition，目标单元：钠及其化合物。"
  },
  {
    "legacyType": "unit",
    "legacyPath": "legacy/prototype-v1/modules/unit-chemistry-sodium.html",
    "legacyTitle": "钠及其化合物",
    "targetSubject": "chemistry",
    "targetModule": "elements-compounds",
    "targetUnitSlug": "chemistry-sodium",
    "action": "migrate-as-is",
    "status": "planned",
    "priority": "medium",
    "notes": "迁入正式知识点页，并按价值补交互 demo。"
  },
  {
    "legacyType": "module",
    "legacyPath": "legacy/prototype-v1/modules/chemistry-experiment.html",
    "legacyTitle": "化学实验与现象",
    "targetSubject": "chemistry",
    "targetModule": "experiments",
    "targetUnitSlug": null,
    "action": "migrate-as-is",
    "status": "planned",
    "priority": "high",
    "notes": "保留模块主线，迁入新站正式模块页。"
  },
  {
    "legacyType": "demo",
    "legacyPath": "legacy/prototype-v1/demos/离子检验演示器",
    "legacyTitle": "离子检验演示器",
    "targetSubject": "chemistry",
    "targetModule": "experiments",
    "targetUnitSlug": "chemistry-ion-identification",
    "action": "rewrite-demo",
    "status": "planned",
    "priority": "medium",
    "notes": "旧演示器重写为正式 DemoDefinition，目标单元：离子检验与实验现象。"
  },
  {
    "legacyType": "unit",
    "legacyPath": "legacy/prototype-v1/modules/unit-chemistry-ion-identification.html",
    "legacyTitle": "离子检验与实验现象",
    "targetSubject": "chemistry",
    "targetModule": "experiments",
    "targetUnitSlug": "chemistry-ion-identification",
    "action": "migrate-as-is",
    "status": "planned",
    "priority": "medium",
    "notes": "迁入正式知识点页，并按价值补交互 demo。"
  },
  {
    "legacyType": "unit",
    "legacyPath": "legacy/prototype-v1/modules/unit-chemistry-lab-devices.html",
    "legacyTitle": "化学实验基础与装置",
    "targetSubject": "chemistry",
    "targetModule": "experiments",
    "targetUnitSlug": "chemistry-lab-devices",
    "action": "migrate-as-is",
    "status": "planned",
    "priority": "medium",
    "notes": "迁入正式知识点页，并按价值补交互 demo。"
  },
  {
    "legacyType": "module",
    "legacyPath": "legacy/prototype-v1/modules/chemistry-reaction.html",
    "legacyTitle": "反应原理与粒子变化",
    "targetSubject": "chemistry",
    "targetModule": "reaction-principles",
    "targetUnitSlug": null,
    "action": "migrate-as-is",
    "status": "planned",
    "priority": "high",
    "notes": "保留模块主线，迁入新站正式模块页。"
  },
  {
    "legacyType": "demo",
    "legacyPath": "legacy/prototype-v1/demos/离子反应与电解质演示器",
    "legacyTitle": "离子反应与电解质演示器",
    "targetSubject": "chemistry",
    "targetModule": "reaction-principles",
    "targetUnitSlug": "chemistry-ionic-reaction",
    "action": "rewrite-demo",
    "status": "planned",
    "priority": "high",
    "notes": "旧演示器重写为正式 DemoDefinition，目标单元：离子反应与电解质。"
  },
  {
    "legacyType": "unit",
    "legacyPath": "legacy/prototype-v1/modules/unit-chemistry-ionic-reaction.html",
    "legacyTitle": "离子反应与电解质",
    "targetSubject": "chemistry",
    "targetModule": "reaction-principles",
    "targetUnitSlug": "chemistry-ionic-reaction",
    "action": "migrate-as-is",
    "status": "planned",
    "priority": "high",
    "notes": "迁入正式知识点页，并按价值补交互 demo。"
  },
  {
    "legacyType": "demo",
    "legacyPath": "legacy/prototype-v1/demos/氧化还原反应演示器",
    "legacyTitle": "氧化还原反应演示器",
    "targetSubject": "chemistry",
    "targetModule": "reaction-principles",
    "targetUnitSlug": "chemistry-redox",
    "action": "rewrite-demo",
    "status": "planned",
    "priority": "high",
    "notes": "旧演示器重写为正式 DemoDefinition，目标单元：氧化还原反应与电子转移。"
  },
  {
    "legacyType": "unit",
    "legacyPath": "legacy/prototype-v1/modules/unit-chemistry-redox.html",
    "legacyTitle": "氧化还原反应与电子转移",
    "targetSubject": "chemistry",
    "targetModule": "reaction-principles",
    "targetUnitSlug": "chemistry-redox",
    "action": "migrate-as-is",
    "status": "planned",
    "priority": "high",
    "notes": "迁入正式知识点页，并按价值补交互 demo。"
  },
  {
    "legacyType": "module",
    "legacyPath": "legacy/prototype-v1/modules/english-roots.html",
    "legacyTitle": "词根词缀与词汇网络",
    "targetSubject": "english",
    "targetModule": "roots-vocabulary-network",
    "targetUnitSlug": null,
    "action": "migrate-as-is",
    "status": "planned",
    "priority": "high",
    "notes": "保留模块主线，迁入新站正式模块页。"
  },
  {
    "legacyType": "unit",
    "legacyPath": "legacy/prototype-v1/modules/unit-english-affix-network.html",
    "legacyTitle": "前后缀变义网络",
    "targetSubject": "english",
    "targetModule": "roots-vocabulary-network",
    "targetUnitSlug": "english-affix-network",
    "action": "migrate-as-is",
    "status": "planned",
    "priority": "medium",
    "notes": "迁入正式知识点页，并按价值补交互 demo。"
  },
  {
    "legacyType": "demo",
    "legacyPath": "legacy/prototype-v1/demos/语法填空策略演示器",
    "legacyTitle": "语法填空策略演示器",
    "targetSubject": "english",
    "targetModule": "roots-vocabulary-network",
    "targetUnitSlug": "english-grammar-cloze-strategy",
    "action": "rewrite-demo",
    "status": "planned",
    "priority": "medium",
    "notes": "旧演示器重写为正式 DemoDefinition，目标单元：语法填空策略演示器。"
  },
  {
    "legacyType": "unit",
    "legacyPath": "legacy/prototype-v1/modules/unit-english-grammar-cloze-strategy.html",
    "legacyTitle": "语法填空策略演示器",
    "targetSubject": "english",
    "targetModule": "roots-vocabulary-network",
    "targetUnitSlug": "english-grammar-cloze-strategy",
    "action": "migrate-as-is",
    "status": "planned",
    "priority": "medium",
    "notes": "迁入正式知识点页，并按价值补交互 demo。"
  },
  {
    "legacyType": "demo",
    "legacyPath": "legacy/prototype-v1/demos/逻辑连接词网络演示器",
    "legacyTitle": "逻辑连接词网络演示器",
    "targetSubject": "english",
    "targetModule": "roots-vocabulary-network",
    "targetUnitSlug": "english-logic-connector-map",
    "action": "rewrite-demo",
    "status": "planned",
    "priority": "medium",
    "notes": "旧演示器重写为正式 DemoDefinition，目标单元：逻辑连接词网络。"
  },
  {
    "legacyType": "unit",
    "legacyPath": "legacy/prototype-v1/modules/unit-english-logic-connector-map.html",
    "legacyTitle": "逻辑连接词网络",
    "targetSubject": "english",
    "targetModule": "roots-vocabulary-network",
    "targetUnitSlug": "english-logic-connector-map",
    "action": "migrate-as-is",
    "status": "planned",
    "priority": "medium",
    "notes": "迁入正式知识点页，并按价值补交互 demo。"
  },
  {
    "legacyType": "demo",
    "legacyPath": "legacy/prototype-v1/demos/近义词语义坐标演示器",
    "legacyTitle": "近义词语义坐标演示器",
    "targetSubject": "english",
    "targetModule": "roots-vocabulary-network",
    "targetUnitSlug": "english-synonym-semantic-map",
    "action": "rewrite-demo",
    "status": "planned",
    "priority": "medium",
    "notes": "旧演示器重写为正式 DemoDefinition，目标单元：近义词语义坐标图。"
  },
  {
    "legacyType": "unit",
    "legacyPath": "legacy/prototype-v1/modules/unit-english-synonym-semantic-map.html",
    "legacyTitle": "近义词语义坐标图",
    "targetSubject": "english",
    "targetModule": "roots-vocabulary-network",
    "targetUnitSlug": "english-synonym-semantic-map",
    "action": "migrate-as-is",
    "status": "planned",
    "priority": "medium",
    "notes": "迁入正式知识点页，并按价值补交互 demo。"
  },
  {
    "legacyType": "unit",
    "legacyPath": "legacy/prototype-v1/modules/unit-english-word-family-atlas.html",
    "legacyTitle": "高频教材词族网络",
    "targetSubject": "english",
    "targetModule": "roots-vocabulary-network",
    "targetUnitSlug": "english-word-family-atlas",
    "action": "migrate-as-is",
    "status": "planned",
    "priority": "medium",
    "notes": "迁入正式知识点页，并按价值补交互 demo。"
  },
  {
    "legacyType": "unit",
    "legacyPath": "legacy/prototype-v1/modules/unit-english-word-roots.html",
    "legacyTitle": "词根归类与词义扩展",
    "targetSubject": "english",
    "targetModule": "roots-vocabulary-network",
    "targetUnitSlug": "english-word-roots",
    "action": "migrate-as-is",
    "status": "planned",
    "priority": "high",
    "notes": "迁入正式知识点页，并按价值补交互 demo。"
  },
  {
    "legacyType": "demo",
    "legacyPath": "legacy/prototype-v1/demos/段落展开工坊演示器",
    "legacyTitle": "段落展开工坊演示器",
    "targetSubject": "english",
    "targetModule": "roots-vocabulary-network",
    "targetUnitSlug": "english-writing-paragraph-workshop",
    "action": "rewrite-demo",
    "status": "planned",
    "priority": "medium",
    "notes": "旧演示器重写为正式 DemoDefinition，目标单元：作文段落展开工坊。"
  },
  {
    "legacyType": "unit",
    "legacyPath": "legacy/prototype-v1/modules/unit-english-writing-paragraph-workshop.html",
    "legacyTitle": "作文段落展开工坊",
    "targetSubject": "english",
    "targetModule": "roots-vocabulary-network",
    "targetUnitSlug": "english-writing-paragraph-workshop",
    "action": "migrate-as-is",
    "status": "planned",
    "priority": "medium",
    "notes": "迁入正式知识点页，并按价值补交互 demo。"
  },
  {
    "legacyType": "unit",
    "legacyPath": "legacy/prototype-v1/modules/unit-english-writing-upgrade-workshop.html",
    "legacyTitle": "写作句型升级工坊",
    "targetSubject": "english",
    "targetModule": "roots-vocabulary-network",
    "targetUnitSlug": "english-writing-upgrade-workshop",
    "action": "migrate-as-is",
    "status": "planned",
    "priority": "medium",
    "notes": "迁入正式知识点页，并按价值补交互 demo。"
  },
  {
    "legacyType": "module",
    "legacyPath": "legacy/prototype-v1/modules/english-sentence.html",
    "legacyTitle": "句子结构与语法拆解",
    "targetSubject": "english",
    "targetModule": "sentence-structure",
    "targetUnitSlug": null,
    "action": "migrate-as-is",
    "status": "planned",
    "priority": "high",
    "notes": "保留模块主线，迁入新站正式模块页。"
  },
  {
    "legacyType": "demo",
    "legacyPath": "legacy/prototype-v1/demos/从句层级演示器",
    "legacyTitle": "从句层级演示器",
    "targetSubject": "english",
    "targetModule": "sentence-structure",
    "targetUnitSlug": "english-clause-hierarchy",
    "action": "rewrite-demo",
    "status": "planned",
    "priority": "medium",
    "notes": "旧演示器重写为正式 DemoDefinition，目标单元：从句层级拆解。"
  },
  {
    "legacyType": "unit",
    "legacyPath": "legacy/prototype-v1/modules/unit-english-clause-hierarchy.html",
    "legacyTitle": "从句层级拆解",
    "targetSubject": "english",
    "targetModule": "sentence-structure",
    "targetUnitSlug": "english-clause-hierarchy",
    "action": "migrate-as-is",
    "status": "planned",
    "priority": "medium",
    "notes": "迁入正式知识点页，并按价值补交互 demo。"
  },
  {
    "legacyType": "demo",
    "legacyPath": "legacy/prototype-v1/demos/听力信息捕捉演示器",
    "legacyTitle": "听力信息捕捉演示器",
    "targetSubject": "english",
    "targetModule": "sentence-structure",
    "targetUnitSlug": "english-listening-capture",
    "action": "rewrite-demo",
    "status": "planned",
    "priority": "medium",
    "notes": "旧演示器重写为正式 DemoDefinition，目标单元：听力信息捕捉流程图。"
  },
  {
    "legacyType": "unit",
    "legacyPath": "legacy/prototype-v1/modules/unit-english-listening-capture.html",
    "legacyTitle": "听力信息捕捉流程图",
    "targetSubject": "english",
    "targetModule": "sentence-structure",
    "targetUnitSlug": "english-listening-capture",
    "action": "migrate-as-is",
    "status": "planned",
    "priority": "medium",
    "notes": "迁入正式知识点页，并按价值补交互 demo。"
  },
  {
    "legacyType": "demo",
    "legacyPath": "legacy/prototype-v1/demos/非谓语结构演示器",
    "legacyTitle": "非谓语结构演示器",
    "targetSubject": "english",
    "targetModule": "sentence-structure",
    "targetUnitSlug": "english-nonfinite-structure",
    "action": "rewrite-demo",
    "status": "planned",
    "priority": "medium",
    "notes": "旧演示器重写为正式 DemoDefinition，目标单元：非谓语结构关系图。"
  },
  {
    "legacyType": "unit",
    "legacyPath": "legacy/prototype-v1/modules/unit-english-nonfinite-structure.html",
    "legacyTitle": "非谓语结构关系图",
    "targetSubject": "english",
    "targetModule": "sentence-structure",
    "targetUnitSlug": "english-nonfinite-structure",
    "action": "migrate-as-is",
    "status": "planned",
    "priority": "medium",
    "notes": "迁入正式知识点页，并按价值补交互 demo。"
  },
  {
    "legacyType": "unit",
    "legacyPath": "legacy/prototype-v1/modules/unit-english-reading-layer.html",
    "legacyTitle": "阅读信息分层",
    "targetSubject": "english",
    "targetModule": "sentence-structure",
    "targetUnitSlug": "english-reading-layer",
    "action": "migrate-as-is",
    "status": "planned",
    "priority": "medium",
    "notes": "迁入正式知识点页，并按价值补交互 demo。"
  },
  {
    "legacyType": "demo",
    "legacyPath": "legacy/prototype-v1/demos/阅读题型拆解演示器",
    "legacyTitle": "阅读题型拆解演示器",
    "targetSubject": "english",
    "targetModule": "sentence-structure",
    "targetUnitSlug": "english-reading-question-map",
    "action": "rewrite-demo",
    "status": "planned",
    "priority": "medium",
    "notes": "旧演示器重写为正式 DemoDefinition，目标单元：阅读题型拆解演示器。"
  },
  {
    "legacyType": "unit",
    "legacyPath": "legacy/prototype-v1/modules/unit-english-reading-question-map.html",
    "legacyTitle": "阅读题型拆解演示器",
    "targetSubject": "english",
    "targetModule": "sentence-structure",
    "targetUnitSlug": "english-reading-question-map",
    "action": "migrate-as-is",
    "status": "planned",
    "priority": "medium",
    "notes": "迁入正式知识点页，并按价值补交互 demo。"
  },
  {
    "legacyType": "unit",
    "legacyPath": "legacy/prototype-v1/modules/unit-english-sentence-compression.html",
    "legacyTitle": "长难句主干压缩",
    "targetSubject": "english",
    "targetModule": "sentence-structure",
    "targetUnitSlug": "english-sentence-compression",
    "action": "migrate-as-is",
    "status": "planned",
    "priority": "medium",
    "notes": "迁入正式知识点页，并按价值补交互 demo。"
  },
  {
    "legacyType": "demo",
    "legacyPath": "legacy/prototype-v1/demos/句子成分演示器",
    "legacyTitle": "句子成分演示器",
    "targetSubject": "english",
    "targetModule": "sentence-structure",
    "targetUnitSlug": "english-sentence-structure",
    "action": "rewrite-demo",
    "status": "planned",
    "priority": "high",
    "notes": "旧演示器重写为正式 DemoDefinition，目标单元：句子成分结构拆解。"
  },
  {
    "legacyType": "unit",
    "legacyPath": "legacy/prototype-v1/modules/unit-english-sentence-structure.html",
    "legacyTitle": "句子成分结构拆解",
    "targetSubject": "english",
    "targetModule": "sentence-structure",
    "targetUnitSlug": "english-sentence-structure",
    "action": "migrate-as-is",
    "status": "planned",
    "priority": "high",
    "notes": "迁入正式知识点页，并按价值补交互 demo。"
  },
  {
    "legacyType": "demo",
    "legacyPath": "legacy/prototype-v1/demos/时态时间轴演示器",
    "legacyTitle": "时态时间轴演示器",
    "targetSubject": "english",
    "targetModule": "sentence-structure",
    "targetUnitSlug": "english-tense-timeline",
    "action": "rewrite-demo",
    "status": "planned",
    "priority": "medium",
    "notes": "旧演示器重写为正式 DemoDefinition，目标单元：语法时态时间轴。"
  },
  {
    "legacyType": "unit",
    "legacyPath": "legacy/prototype-v1/modules/unit-english-tense-timeline.html",
    "legacyTitle": "语法时态时间轴",
    "targetSubject": "english",
    "targetModule": "sentence-structure",
    "targetUnitSlug": "english-tense-timeline",
    "action": "migrate-as-is",
    "status": "planned",
    "priority": "medium",
    "notes": "迁入正式知识点页，并按价值补交互 demo。"
  },
  {
    "legacyType": "module",
    "legacyPath": "legacy/prototype-v1/modules/analytic-geometry.html",
    "legacyTitle": "解析几何",
    "targetSubject": "math",
    "targetModule": "analytic-geometry",
    "targetUnitSlug": null,
    "action": "migrate-as-is",
    "status": "planned",
    "priority": "high",
    "notes": "保留模块主线，迁入新站正式模块页。"
  },
  {
    "legacyType": "demo",
    "legacyPath": "legacy/prototype-v1/demos/圆的标准方程演示器",
    "legacyTitle": "圆的标准方程演示器",
    "targetSubject": "math",
    "targetModule": "analytic-geometry",
    "targetUnitSlug": "circle-standard",
    "action": "rewrite-demo",
    "status": "planned",
    "priority": "medium",
    "notes": "旧演示器重写为正式 DemoDefinition，目标单元：圆的标准方程与图像。"
  },
  {
    "legacyType": "unit",
    "legacyPath": "legacy/prototype-v1/modules/unit-circle-standard.html",
    "legacyTitle": "圆的标准方程与图像",
    "targetSubject": "math",
    "targetModule": "analytic-geometry",
    "targetUnitSlug": "circle-standard",
    "action": "migrate-as-is",
    "status": "planned",
    "priority": "medium",
    "notes": "迁入正式知识点页，并按价值补交互 demo。"
  },
  {
    "legacyType": "demo",
    "legacyPath": "legacy/prototype-v1/demos/圆锥曲线总览演示器",
    "legacyTitle": "圆锥曲线总览演示器",
    "targetSubject": "math",
    "targetModule": "analytic-geometry",
    "targetUnitSlug": "conic-overview",
    "action": "rewrite-demo",
    "status": "planned",
    "priority": "medium",
    "notes": "旧演示器重写为正式 DemoDefinition，目标单元：圆锥曲线总览与对比。"
  },
  {
    "legacyType": "unit",
    "legacyPath": "legacy/prototype-v1/modules/unit-conic-overview.html",
    "legacyTitle": "圆锥曲线总览与对比",
    "targetSubject": "math",
    "targetModule": "analytic-geometry",
    "targetUnitSlug": "conic-overview",
    "action": "migrate-as-is",
    "status": "planned",
    "priority": "medium",
    "notes": "迁入正式知识点页，并按价值补交互 demo。"
  },
  {
    "legacyType": "demo",
    "legacyPath": "legacy/prototype-v1/demos/椭圆标准方程演示器",
    "legacyTitle": "椭圆标准方程演示器",
    "targetSubject": "math",
    "targetModule": "analytic-geometry",
    "targetUnitSlug": "ellipse-standard",
    "action": "rewrite-demo",
    "status": "planned",
    "priority": "medium",
    "notes": "旧演示器重写为正式 DemoDefinition，目标单元：椭圆标准方程与长短轴变化。"
  },
  {
    "legacyType": "unit",
    "legacyPath": "legacy/prototype-v1/modules/unit-ellipse-standard.html",
    "legacyTitle": "椭圆标准方程与长短轴变化",
    "targetSubject": "math",
    "targetModule": "analytic-geometry",
    "targetUnitSlug": "ellipse-standard",
    "action": "migrate-as-is",
    "status": "planned",
    "priority": "medium",
    "notes": "迁入正式知识点页，并按价值补交互 demo。"
  },
  {
    "legacyType": "demo",
    "legacyPath": "legacy/prototype-v1/demos/双曲线标准方程演示器",
    "legacyTitle": "双曲线标准方程演示器",
    "targetSubject": "math",
    "targetModule": "analytic-geometry",
    "targetUnitSlug": "hyperbola-standard",
    "action": "rewrite-demo",
    "status": "planned",
    "priority": "medium",
    "notes": "旧演示器重写为正式 DemoDefinition，目标单元：双曲线标准方程与渐近线变化。"
  },
  {
    "legacyType": "unit",
    "legacyPath": "legacy/prototype-v1/modules/unit-hyperbola-standard.html",
    "legacyTitle": "双曲线标准方程与渐近线变化",
    "targetSubject": "math",
    "targetModule": "analytic-geometry",
    "targetUnitSlug": "hyperbola-standard",
    "action": "migrate-as-is",
    "status": "planned",
    "priority": "medium",
    "notes": "迁入正式知识点页，并按价值补交互 demo。"
  },
  {
    "legacyType": "demo",
    "legacyPath": "legacy/prototype-v1/demos/直线与圆演示器",
    "legacyTitle": "直线与圆演示器",
    "targetSubject": "math",
    "targetModule": "analytic-geometry",
    "targetUnitSlug": "line-circle",
    "action": "rewrite-demo",
    "status": "planned",
    "priority": "high",
    "notes": "旧演示器重写为正式 DemoDefinition，目标单元：直线与圆的位置关系。"
  },
  {
    "legacyType": "unit",
    "legacyPath": "legacy/prototype-v1/modules/unit-line-circle.html",
    "legacyTitle": "直线与圆的位置关系",
    "targetSubject": "math",
    "targetModule": "analytic-geometry",
    "targetUnitSlug": "line-circle",
    "action": "migrate-as-is",
    "status": "planned",
    "priority": "high",
    "notes": "迁入正式知识点页，并按价值补交互 demo。"
  },
  {
    "legacyType": "demo",
    "legacyPath": "legacy/prototype-v1/demos/直线与圆锥曲线位置关系演示器",
    "legacyTitle": "直线与圆锥曲线位置关系演示器",
    "targetSubject": "math",
    "targetModule": "analytic-geometry",
    "targetUnitSlug": "line-conic-relation",
    "action": "rewrite-demo",
    "status": "planned",
    "priority": "medium",
    "notes": "旧演示器重写为正式 DemoDefinition，目标单元：直线与圆锥曲线位置关系。"
  },
  {
    "legacyType": "unit",
    "legacyPath": "legacy/prototype-v1/modules/unit-line-conic-relation.html",
    "legacyTitle": "直线与圆锥曲线位置关系",
    "targetSubject": "math",
    "targetModule": "analytic-geometry",
    "targetUnitSlug": "line-conic-relation",
    "action": "migrate-as-is",
    "status": "planned",
    "priority": "medium",
    "notes": "迁入正式知识点页，并按价值补交互 demo。"
  },
  {
    "legacyType": "demo",
    "legacyPath": "legacy/prototype-v1/demos/抛物线标准方程演示器",
    "legacyTitle": "抛物线标准方程演示器",
    "targetSubject": "math",
    "targetModule": "analytic-geometry",
    "targetUnitSlug": "parabola-standard",
    "action": "rewrite-demo",
    "status": "planned",
    "priority": "medium",
    "notes": "旧演示器重写为正式 DemoDefinition，目标单元：抛物线标准方程与开口变化。"
  },
  {
    "legacyType": "unit",
    "legacyPath": "legacy/prototype-v1/modules/unit-parabola-standard.html",
    "legacyTitle": "抛物线标准方程与开口变化",
    "targetSubject": "math",
    "targetModule": "analytic-geometry",
    "targetUnitSlug": "parabola-standard",
    "action": "migrate-as-is",
    "status": "planned",
    "priority": "medium",
    "notes": "迁入正式知识点页，并按价值补交互 demo。"
  },
  {
    "legacyType": "demo",
    "legacyPath": "legacy/prototype-v1/demos/点到直线距离演示器",
    "legacyTitle": "点到直线距离演示器",
    "targetSubject": "math",
    "targetModule": "analytic-geometry",
    "targetUnitSlug": "point-line-distance",
    "action": "rewrite-demo",
    "status": "planned",
    "priority": "medium",
    "notes": "旧演示器重写为正式 DemoDefinition，目标单元：点到直线距离的图形理解。"
  },
  {
    "legacyType": "unit",
    "legacyPath": "legacy/prototype-v1/modules/unit-point-line-distance.html",
    "legacyTitle": "点到直线距离的图形理解",
    "targetSubject": "math",
    "targetModule": "analytic-geometry",
    "targetUnitSlug": "point-line-distance",
    "action": "migrate-as-is",
    "status": "planned",
    "priority": "medium",
    "notes": "迁入正式知识点页，并按价值补交互 demo。"
  },
  {
    "legacyType": "demo",
    "legacyPath": "legacy/prototype-v1/demos/sin函数演示器",
    "legacyTitle": "sin函数演示器",
    "targetSubject": "math",
    "targetModule": "functions",
    "targetUnitSlug": null,
    "action": "archive-only",
    "status": "planned",
    "priority": "medium",
    "notes": "暂未自动匹配到单元，先保留在归档区等待人工归类。"
  },
  {
    "legacyType": "demo",
    "legacyPath": "legacy/prototype-v1/demos/写作升级工坊演示器",
    "legacyTitle": "写作升级工坊演示器",
    "targetSubject": "math",
    "targetModule": "functions",
    "targetUnitSlug": null,
    "action": "archive-only",
    "status": "planned",
    "priority": "medium",
    "notes": "暂未自动匹配到单元，先保留在归档区等待人工归类。"
  },
  {
    "legacyType": "demo",
    "legacyPath": "legacy/prototype-v1/demos/函数变换演示器",
    "legacyTitle": "函数变换演示器",
    "targetSubject": "math",
    "targetModule": "functions",
    "targetUnitSlug": null,
    "action": "archive-only",
    "status": "planned",
    "priority": "medium",
    "notes": "暂未自动匹配到单元，先保留在归档区等待人工归类。"
  },
  {
    "legacyType": "demo",
    "legacyPath": "legacy/prototype-v1/demos/前后缀网络演示器",
    "legacyTitle": "前后缀网络演示器",
    "targetSubject": "math",
    "targetModule": "functions",
    "targetUnitSlug": null,
    "action": "archive-only",
    "status": "planned",
    "priority": "medium",
    "notes": "暂未自动匹配到单元，先保留在归档区等待人工归类。"
  },
  {
    "legacyType": "demo",
    "legacyPath": "legacy/prototype-v1/demos/实验装置演示器",
    "legacyTitle": "实验装置演示器",
    "targetSubject": "math",
    "targetModule": "functions",
    "targetUnitSlug": null,
    "action": "archive-only",
    "status": "planned",
    "priority": "medium",
    "notes": "暂未自动匹配到单元，先保留在归档区等待人工归类。"
  },
  {
    "legacyType": "demo",
    "legacyPath": "legacy/prototype-v1/demos/指数与对数演示器",
    "legacyTitle": "指数与对数演示器",
    "targetSubject": "math",
    "targetModule": "functions",
    "targetUnitSlug": null,
    "action": "archive-only",
    "status": "planned",
    "priority": "medium",
    "notes": "暂未自动匹配到单元，先保留在归档区等待人工归类。"
  },
  {
    "legacyType": "demo",
    "legacyPath": "legacy/prototype-v1/demos/立体截面演示器",
    "legacyTitle": "立体截面演示器",
    "targetSubject": "math",
    "targetModule": "functions",
    "targetUnitSlug": null,
    "action": "archive-only",
    "status": "planned",
    "priority": "medium",
    "notes": "暂未自动匹配到单元，先保留在归档区等待人工归类。"
  },
  {
    "legacyType": "demo",
    "legacyPath": "legacy/prototype-v1/demos/等差等比数列演示器",
    "legacyTitle": "等差等比数列演示器",
    "targetSubject": "math",
    "targetModule": "functions",
    "targetUnitSlug": null,
    "action": "archive-only",
    "status": "planned",
    "priority": "medium",
    "notes": "暂未自动匹配到单元，先保留在归档区等待人工归类。"
  },
  {
    "legacyType": "demo",
    "legacyPath": "legacy/prototype-v1/demos/词根词缀演示器",
    "legacyTitle": "词根词缀演示器",
    "targetSubject": "math",
    "targetModule": "functions",
    "targetUnitSlug": null,
    "action": "archive-only",
    "status": "planned",
    "priority": "medium",
    "notes": "暂未自动匹配到单元，先保留在归档区等待人工归类。"
  },
  {
    "legacyType": "demo",
    "legacyPath": "legacy/prototype-v1/demos/长难句压缩演示器",
    "legacyTitle": "长难句压缩演示器",
    "targetSubject": "math",
    "targetModule": "functions",
    "targetUnitSlug": null,
    "action": "archive-only",
    "status": "planned",
    "priority": "medium",
    "notes": "暂未自动匹配到单元，先保留在归档区等待人工归类。"
  },
  {
    "legacyType": "demo",
    "legacyPath": "legacy/prototype-v1/demos/阅读分层演示器",
    "legacyTitle": "阅读分层演示器",
    "targetSubject": "math",
    "targetModule": "functions",
    "targetUnitSlug": null,
    "action": "archive-only",
    "status": "planned",
    "priority": "medium",
    "notes": "暂未自动匹配到单元，先保留在归档区等待人工归类。"
  },
  {
    "legacyType": "demo",
    "legacyPath": "legacy/prototype-v1/demos/高频词族网络演示器",
    "legacyTitle": "高频词族网络演示器",
    "targetSubject": "math",
    "targetModule": "functions",
    "targetUnitSlug": null,
    "action": "archive-only",
    "status": "planned",
    "priority": "medium",
    "notes": "暂未自动匹配到单元，先保留在归档区等待人工归类。"
  },
  {
    "legacyType": "module",
    "legacyPath": "legacy/prototype-v1/modules/functions.html",
    "legacyTitle": "函数与图像",
    "targetSubject": "math",
    "targetModule": "functions",
    "targetUnitSlug": null,
    "action": "migrate-as-is",
    "status": "planned",
    "priority": "high",
    "notes": "保留模块主线，迁入新站正式模块页。"
  },
  {
    "legacyType": "unit",
    "legacyPath": "legacy/prototype-v1/modules/unit-exp-log.html",
    "legacyTitle": "指数函数与对数函数对比",
    "targetSubject": "math",
    "targetModule": "functions",
    "targetUnitSlug": "exp-log",
    "action": "migrate-as-is",
    "status": "planned",
    "priority": "high",
    "notes": "迁入正式知识点页，并按价值补交互 demo。"
  },
  {
    "legacyType": "demo",
    "legacyPath": "legacy/prototype-v1/demos/一次函数演示器",
    "legacyTitle": "一次函数演示器",
    "targetSubject": "math",
    "targetModule": "functions",
    "targetUnitSlug": "linear",
    "action": "rewrite-demo",
    "status": "planned",
    "priority": "high",
    "notes": "旧演示器重写为正式 DemoDefinition，目标单元：一次函数变化。"
  },
  {
    "legacyType": "unit",
    "legacyPath": "legacy/prototype-v1/modules/unit-linear.html",
    "legacyTitle": "一次函数变化",
    "targetSubject": "math",
    "targetModule": "functions",
    "targetUnitSlug": "linear",
    "action": "migrate-as-is",
    "status": "planned",
    "priority": "high",
    "notes": "迁入正式知识点页，并按价值补交互 demo。"
  },
  {
    "legacyType": "demo",
    "legacyPath": "legacy/prototype-v1/demos/幂函数演示器",
    "legacyTitle": "幂函数演示器",
    "targetSubject": "math",
    "targetModule": "functions",
    "targetUnitSlug": "power",
    "action": "rewrite-demo",
    "status": "planned",
    "priority": "medium",
    "notes": "旧演示器重写为正式 DemoDefinition，目标单元：幂函数与图像变化。"
  },
  {
    "legacyType": "unit",
    "legacyPath": "legacy/prototype-v1/modules/unit-power.html",
    "legacyTitle": "幂函数与图像变化",
    "targetSubject": "math",
    "targetModule": "functions",
    "targetUnitSlug": "power",
    "action": "migrate-as-is",
    "status": "planned",
    "priority": "medium",
    "notes": "迁入正式知识点页，并按价值补交互 demo。"
  },
  {
    "legacyType": "demo",
    "legacyPath": "legacy/prototype-v1/demos/函数变化演示器",
    "legacyTitle": "函数变化演示器",
    "targetSubject": "math",
    "targetModule": "functions",
    "targetUnitSlug": "quadratic",
    "action": "rewrite-demo",
    "status": "planned",
    "priority": "high",
    "notes": "旧演示器重写为正式 DemoDefinition，目标单元：二次函数变化。"
  },
  {
    "legacyType": "unit",
    "legacyPath": "legacy/prototype-v1/modules/unit-quadratic.html",
    "legacyTitle": "二次函数变化",
    "targetSubject": "math",
    "targetModule": "functions",
    "targetUnitSlug": "quadratic",
    "action": "migrate-as-is",
    "status": "planned",
    "priority": "high",
    "notes": "迁入正式知识点页，并按价值补交互 demo。"
  },
  {
    "legacyType": "demo",
    "legacyPath": "legacy/prototype-v1/demos/反比例函数演示器",
    "legacyTitle": "反比例函数演示器",
    "targetSubject": "math",
    "targetModule": "functions",
    "targetUnitSlug": "reciprocal",
    "action": "rewrite-demo",
    "status": "planned",
    "priority": "medium",
    "notes": "旧演示器重写为正式 DemoDefinition，目标单元：反比例函数变化。"
  },
  {
    "legacyType": "unit",
    "legacyPath": "legacy/prototype-v1/modules/unit-reciprocal.html",
    "legacyTitle": "反比例函数变化",
    "targetSubject": "math",
    "targetModule": "functions",
    "targetUnitSlug": "reciprocal",
    "action": "migrate-as-is",
    "status": "planned",
    "priority": "medium",
    "notes": "迁入正式知识点页，并按价值补交互 demo。"
  },
  {
    "legacyType": "unit",
    "legacyPath": "legacy/prototype-v1/modules/unit-transform-review.html",
    "legacyTitle": "函数平移与伸缩总复习",
    "targetSubject": "math",
    "targetModule": "functions",
    "targetUnitSlug": "transform-review",
    "action": "migrate-as-is",
    "status": "planned",
    "priority": "medium",
    "notes": "迁入正式知识点页，并按价值补交互 demo。"
  },
  {
    "legacyType": "module",
    "legacyPath": "legacy/prototype-v1/modules/sequences.html",
    "legacyTitle": "数列与递推模型",
    "targetSubject": "math",
    "targetModule": "sequences",
    "targetUnitSlug": null,
    "action": "migrate-as-is",
    "status": "planned",
    "priority": "high",
    "notes": "保留模块主线，迁入新站正式模块页。"
  },
  {
    "legacyType": "demo",
    "legacyPath": "legacy/prototype-v1/demos/递推数列演示器",
    "legacyTitle": "递推数列演示器",
    "targetSubject": "math",
    "targetModule": "sequences",
    "targetUnitSlug": "sequence-recursive",
    "action": "rewrite-demo",
    "status": "planned",
    "priority": "medium",
    "notes": "旧演示器重写为正式 DemoDefinition，目标单元：递推数列生成过程。"
  },
  {
    "legacyType": "unit",
    "legacyPath": "legacy/prototype-v1/modules/unit-sequence-recursive.html",
    "legacyTitle": "递推数列生成过程",
    "targetSubject": "math",
    "targetModule": "sequences",
    "targetUnitSlug": "sequence-recursive",
    "action": "migrate-as-is",
    "status": "planned",
    "priority": "medium",
    "notes": "迁入正式知识点页，并按价值补交互 demo。"
  },
  {
    "legacyType": "unit",
    "legacyPath": "legacy/prototype-v1/modules/unit-sequences-basic.html",
    "legacyTitle": "等差与等比数列生成过程",
    "targetSubject": "math",
    "targetModule": "sequences",
    "targetUnitSlug": "sequences-basic",
    "action": "migrate-as-is",
    "status": "planned",
    "priority": "high",
    "notes": "迁入正式知识点页，并按价值补交互 demo。"
  },
  {
    "legacyType": "module",
    "legacyPath": "legacy/prototype-v1/modules/sets-logic.html",
    "legacyTitle": "集合与逻辑",
    "targetSubject": "math",
    "targetModule": "sets-logic",
    "targetUnitSlug": null,
    "action": "migrate-as-is",
    "status": "planned",
    "priority": "high",
    "notes": "保留模块主线，迁入新站正式模块页。"
  },
  {
    "legacyType": "demo",
    "legacyPath": "legacy/prototype-v1/demos/集合运算与韦恩图演示器",
    "legacyTitle": "集合运算与韦恩图演示器",
    "targetSubject": "math",
    "targetModule": "sets-logic",
    "targetUnitSlug": "set-operations",
    "action": "rewrite-demo",
    "status": "planned",
    "priority": "high",
    "notes": "旧演示器重写为正式 DemoDefinition，目标单元：集合运算与韦恩图。"
  },
  {
    "legacyType": "unit",
    "legacyPath": "legacy/prototype-v1/modules/unit-set-operations.html",
    "legacyTitle": "集合运算与韦恩图",
    "targetSubject": "math",
    "targetModule": "sets-logic",
    "targetUnitSlug": "set-operations",
    "action": "migrate-as-is",
    "status": "planned",
    "priority": "high",
    "notes": "迁入正式知识点页，并按价值补交互 demo。"
  },
  {
    "legacyType": "demo",
    "legacyPath": "legacy/prototype-v1/demos/集合基础概念演示器",
    "legacyTitle": "集合基础概念演示器",
    "targetSubject": "math",
    "targetModule": "sets-logic",
    "targetUnitSlug": "sets-basics",
    "action": "rewrite-demo",
    "status": "planned",
    "priority": "high",
    "notes": "旧演示器重写为正式 DemoDefinition，目标单元：集合基础概念。"
  },
  {
    "legacyType": "unit",
    "legacyPath": "legacy/prototype-v1/modules/unit-sets-basics.html",
    "legacyTitle": "集合基础概念",
    "targetSubject": "math",
    "targetModule": "sets-logic",
    "targetUnitSlug": "sets-basics",
    "action": "migrate-as-is",
    "status": "planned",
    "priority": "high",
    "notes": "迁入正式知识点页，并按价值补交互 demo。"
  },
  {
    "legacyType": "module",
    "legacyPath": "legacy/prototype-v1/modules/solid-geometry.html",
    "legacyTitle": "立体几何",
    "targetSubject": "math",
    "targetModule": "solid-geometry",
    "targetUnitSlug": null,
    "action": "migrate-as-is",
    "status": "planned",
    "priority": "high",
    "notes": "保留模块主线，迁入新站正式模块页。"
  },
  {
    "legacyType": "demo",
    "legacyPath": "legacy/prototype-v1/demos/旋转体生成演示器",
    "legacyTitle": "旋转体生成演示器",
    "targetSubject": "math",
    "targetModule": "solid-geometry",
    "targetUnitSlug": "solid-rotation",
    "action": "rewrite-demo",
    "status": "planned",
    "priority": "medium",
    "notes": "旧演示器重写为正式 DemoDefinition，目标单元：旋转体生成过程。"
  },
  {
    "legacyType": "unit",
    "legacyPath": "legacy/prototype-v1/modules/unit-solid-rotation.html",
    "legacyTitle": "旋转体生成过程",
    "targetSubject": "math",
    "targetModule": "solid-geometry",
    "targetUnitSlug": "solid-rotation",
    "action": "migrate-as-is",
    "status": "planned",
    "priority": "medium",
    "notes": "迁入正式知识点页，并按价值补交互 demo。"
  },
  {
    "legacyType": "unit",
    "legacyPath": "legacy/prototype-v1/modules/unit-solid-section.html",
    "legacyTitle": "立体几何体与截面变化",
    "targetSubject": "math",
    "targetModule": "solid-geometry",
    "targetUnitSlug": "solid-section",
    "action": "migrate-as-is",
    "status": "planned",
    "priority": "high",
    "notes": "迁入正式知识点页，并按价值补交互 demo。"
  },
  {
    "legacyType": "module",
    "legacyPath": "legacy/prototype-v1/modules/trigonometry.html",
    "legacyTitle": "三角函数与周期模型",
    "targetSubject": "math",
    "targetModule": "trigonometry",
    "targetUnitSlug": null,
    "action": "migrate-as-is",
    "status": "planned",
    "priority": "high",
    "notes": "保留模块主线，迁入新站正式模块页。"
  },
  {
    "legacyType": "demo",
    "legacyPath": "legacy/prototype-v1/demos/余弦函数演示器",
    "legacyTitle": "余弦函数演示器",
    "targetSubject": "math",
    "targetModule": "trigonometry",
    "targetUnitSlug": "cos-basic",
    "action": "rewrite-demo",
    "status": "planned",
    "priority": "medium",
    "notes": "旧演示器重写为正式 DemoDefinition，目标单元：余弦函数基础图像。"
  },
  {
    "legacyType": "unit",
    "legacyPath": "legacy/prototype-v1/modules/unit-cos-basic.html",
    "legacyTitle": "余弦函数基础图像",
    "targetSubject": "math",
    "targetModule": "trigonometry",
    "targetUnitSlug": "cos-basic",
    "action": "migrate-as-is",
    "status": "planned",
    "priority": "medium",
    "notes": "迁入正式知识点页，并按价值补交互 demo。"
  },
  {
    "legacyType": "unit",
    "legacyPath": "legacy/prototype-v1/modules/unit-sin-basic.html",
    "legacyTitle": "sin(x) 基础图像",
    "targetSubject": "math",
    "targetModule": "trigonometry",
    "targetUnitSlug": "sin-basic",
    "action": "migrate-as-is",
    "status": "planned",
    "priority": "high",
    "notes": "迁入正式知识点页，并按价值补交互 demo。"
  },
  {
    "legacyType": "demo",
    "legacyPath": "legacy/prototype-v1/demos/三角函数参数演示器",
    "legacyTitle": "三角函数参数演示器",
    "targetSubject": "math",
    "targetModule": "trigonometry",
    "targetUnitSlug": "sin-transform",
    "action": "rewrite-demo",
    "status": "planned",
    "priority": "high",
    "notes": "旧演示器重写为正式 DemoDefinition，目标单元：三角函数参数变化。"
  },
  {
    "legacyType": "unit",
    "legacyPath": "legacy/prototype-v1/modules/unit-sin-transform.html",
    "legacyTitle": "三角函数参数变化",
    "targetSubject": "math",
    "targetModule": "trigonometry",
    "targetUnitSlug": "sin-transform",
    "action": "migrate-as-is",
    "status": "planned",
    "priority": "high",
    "notes": "迁入正式知识点页，并按价值补交互 demo。"
  },
  {
    "legacyType": "demo",
    "legacyPath": "legacy/prototype-v1/demos/正切函数演示器",
    "legacyTitle": "正切函数演示器",
    "targetSubject": "math",
    "targetModule": "trigonometry",
    "targetUnitSlug": "tan-basic",
    "action": "rewrite-demo",
    "status": "planned",
    "priority": "medium",
    "notes": "旧演示器重写为正式 DemoDefinition，目标单元：正切函数与间断感知。"
  },
  {
    "legacyType": "unit",
    "legacyPath": "legacy/prototype-v1/modules/unit-tan-basic.html",
    "legacyTitle": "正切函数与间断感知",
    "targetSubject": "math",
    "targetModule": "trigonometry",
    "targetUnitSlug": "tan-basic",
    "action": "migrate-as-is",
    "status": "planned",
    "priority": "medium",
    "notes": "迁入正式知识点页，并按价值补交互 demo。"
  },
  {
    "legacyType": "module",
    "legacyPath": "legacy/prototype-v1/modules/physics-electricity.html",
    "legacyTitle": "电学与电路",
    "targetSubject": "physics",
    "targetModule": "electricity",
    "targetUnitSlug": null,
    "action": "migrate-as-is",
    "status": "planned",
    "priority": "high",
    "notes": "保留模块主线，迁入新站正式模块页。"
  },
  {
    "legacyType": "unit",
    "legacyPath": "legacy/prototype-v1/modules/unit-physics-ohms-law.html",
    "legacyTitle": "欧姆定律与伏安关系",
    "targetSubject": "physics",
    "targetModule": "electricity",
    "targetUnitSlug": "physics-ohms-law",
    "action": "migrate-as-is",
    "status": "planned",
    "priority": "medium",
    "notes": "迁入正式知识点页，并按价值补交互 demo。"
  },
  {
    "legacyType": "unit",
    "legacyPath": "legacy/prototype-v1/modules/unit-physics-series-parallel.html",
    "legacyTitle": "串联与并联电路对比",
    "targetSubject": "physics",
    "targetModule": "electricity",
    "targetUnitSlug": "physics-series-parallel",
    "action": "migrate-as-is",
    "status": "planned",
    "priority": "medium",
    "notes": "迁入正式知识点页，并按价值补交互 demo。"
  },
  {
    "legacyType": "module",
    "legacyPath": "legacy/prototype-v1/modules/physics-energy.html",
    "legacyTitle": "功与能量",
    "targetSubject": "physics",
    "targetModule": "energy",
    "targetUnitSlug": null,
    "action": "migrate-as-is",
    "status": "planned",
    "priority": "high",
    "notes": "保留模块主线，迁入新站正式模块页。"
  },
  {
    "legacyType": "unit",
    "legacyPath": "legacy/prototype-v1/modules/unit-physics-kinetic-energy.html",
    "legacyTitle": "动能定理",
    "targetSubject": "physics",
    "targetModule": "energy",
    "targetUnitSlug": "physics-kinetic-energy",
    "action": "migrate-as-is",
    "status": "planned",
    "priority": "medium",
    "notes": "迁入正式知识点页，并按价值补交互 demo。"
  },
  {
    "legacyType": "demo",
    "legacyPath": "legacy/prototype-v1/demos/机械能守恒演示器",
    "legacyTitle": "机械能守恒演示器",
    "targetSubject": "physics",
    "targetModule": "energy",
    "targetUnitSlug": "physics-mechanical-energy",
    "action": "rewrite-demo",
    "status": "planned",
    "priority": "medium",
    "notes": "旧演示器重写为正式 DemoDefinition，目标单元：机械能守恒。"
  },
  {
    "legacyType": "unit",
    "legacyPath": "legacy/prototype-v1/modules/unit-physics-mechanical-energy.html",
    "legacyTitle": "机械能守恒",
    "targetSubject": "physics",
    "targetModule": "energy",
    "targetUnitSlug": "physics-mechanical-energy",
    "action": "migrate-as-is",
    "status": "planned",
    "priority": "medium",
    "notes": "迁入正式知识点页，并按价值补交互 demo。"
  },
  {
    "legacyType": "demo",
    "legacyPath": "legacy/prototype-v1/demos/功能量综合应用演示器",
    "legacyTitle": "功能量综合应用演示器",
    "targetSubject": "physics",
    "targetModule": "energy",
    "targetUnitSlug": "physics-work-energy-synthesis",
    "action": "rewrite-demo",
    "status": "planned",
    "priority": "medium",
    "notes": "旧演示器重写为正式 DemoDefinition，目标单元：功能量综合应用。"
  },
  {
    "legacyType": "unit",
    "legacyPath": "legacy/prototype-v1/modules/unit-physics-work-energy-synthesis.html",
    "legacyTitle": "功能量综合应用",
    "targetSubject": "physics",
    "targetModule": "energy",
    "targetUnitSlug": "physics-work-energy-synthesis",
    "action": "migrate-as-is",
    "status": "planned",
    "priority": "medium",
    "notes": "迁入正式知识点页，并按价值补交互 demo。"
  },
  {
    "legacyType": "unit",
    "legacyPath": "legacy/prototype-v1/modules/unit-physics-work-power.html",
    "legacyTitle": "功与功率",
    "targetSubject": "physics",
    "targetModule": "energy",
    "targetUnitSlug": "physics-work-power",
    "action": "migrate-as-is",
    "status": "planned",
    "priority": "medium",
    "notes": "迁入正式知识点页，并按价值补交互 demo。"
  },
  {
    "legacyType": "module",
    "legacyPath": "legacy/prototype-v1/modules/physics-force.html",
    "legacyTitle": "力与受力分析",
    "targetSubject": "physics",
    "targetModule": "force",
    "targetUnitSlug": null,
    "action": "migrate-as-is",
    "status": "planned",
    "priority": "high",
    "notes": "保留模块主线，迁入新站正式模块页。"
  },
  {
    "legacyType": "demo",
    "legacyPath": "legacy/prototype-v1/demos/连接体受力演示器",
    "legacyTitle": "连接体受力演示器",
    "targetSubject": "physics",
    "targetModule": "force",
    "targetUnitSlug": "physics-connected-bodies",
    "action": "rewrite-demo",
    "status": "planned",
    "priority": "medium",
    "notes": "旧演示器重写为正式 DemoDefinition，目标单元：连接体受力与整体隔离。"
  },
  {
    "legacyType": "unit",
    "legacyPath": "legacy/prototype-v1/modules/unit-physics-connected-bodies.html",
    "legacyTitle": "连接体受力与整体隔离",
    "targetSubject": "physics",
    "targetModule": "force",
    "targetUnitSlug": "physics-connected-bodies",
    "action": "migrate-as-is",
    "status": "planned",
    "priority": "medium",
    "notes": "迁入正式知识点页，并按价值补交互 demo。"
  },
  {
    "legacyType": "unit",
    "legacyPath": "legacy/prototype-v1/modules/unit-physics-force-balance.html",
    "legacyTitle": "共点力平衡与受力平衡",
    "targetSubject": "physics",
    "targetModule": "force",
    "targetUnitSlug": "physics-force-balance",
    "action": "migrate-as-is",
    "status": "planned",
    "priority": "medium",
    "notes": "迁入正式知识点页，并按价值补交互 demo。"
  },
  {
    "legacyType": "unit",
    "legacyPath": "legacy/prototype-v1/modules/unit-physics-force-composition.html",
    "legacyTitle": "力的合成与分解",
    "targetSubject": "physics",
    "targetModule": "force",
    "targetUnitSlug": "physics-force-composition",
    "action": "migrate-as-is",
    "status": "planned",
    "priority": "high",
    "notes": "迁入正式知识点页，并按价值补交互 demo。"
  },
  {
    "legacyType": "unit",
    "legacyPath": "legacy/prototype-v1/modules/unit-physics-friction.html",
    "legacyTitle": "摩擦力与临界状态",
    "targetSubject": "physics",
    "targetModule": "force",
    "targetUnitSlug": "physics-friction",
    "action": "migrate-as-is",
    "status": "planned",
    "priority": "medium",
    "notes": "迁入正式知识点页，并按价值补交互 demo。"
  },
  {
    "legacyType": "unit",
    "legacyPath": "legacy/prototype-v1/modules/unit-physics-incline-motion.html",
    "legacyTitle": "斜面受力与运动",
    "targetSubject": "physics",
    "targetModule": "force",
    "targetUnitSlug": "physics-incline-motion",
    "action": "migrate-as-is",
    "status": "planned",
    "priority": "medium",
    "notes": "迁入正式知识点页，并按价值补交互 demo。"
  },
  {
    "legacyType": "unit",
    "legacyPath": "legacy/prototype-v1/modules/unit-physics-newton-second-law.html",
    "legacyTitle": "牛顿第二定律的变量关系",
    "targetSubject": "physics",
    "targetModule": "force",
    "targetUnitSlug": "physics-newton-second-law",
    "action": "migrate-as-is",
    "status": "planned",
    "priority": "high",
    "notes": "迁入正式知识点页，并按价值补交互 demo。"
  },
  {
    "legacyType": "demo",
    "legacyPath": "legacy/prototype-v1/demos/超重与失重演示器",
    "legacyTitle": "超重与失重演示器",
    "targetSubject": "physics",
    "targetModule": "force",
    "targetUnitSlug": "physics-overweight-weightlessness",
    "action": "rewrite-demo",
    "status": "planned",
    "priority": "medium",
    "notes": "旧演示器重写为正式 DemoDefinition，目标单元：超重与失重。"
  },
  {
    "legacyType": "unit",
    "legacyPath": "legacy/prototype-v1/modules/unit-physics-overweight-weightlessness.html",
    "legacyTitle": "超重与失重",
    "targetSubject": "physics",
    "targetModule": "force",
    "targetUnitSlug": "physics-overweight-weightlessness",
    "action": "migrate-as-is",
    "status": "planned",
    "priority": "medium",
    "notes": "迁入正式知识点页，并按价值补交互 demo。"
  },
  {
    "legacyType": "module",
    "legacyPath": "legacy/prototype-v1/modules/physics-motion.html",
    "legacyTitle": "运动与图像",
    "targetSubject": "physics",
    "targetModule": "motion",
    "targetUnitSlug": null,
    "action": "migrate-as-is",
    "status": "planned",
    "priority": "high",
    "notes": "保留模块主线，迁入新站正式模块页。"
  },
  {
    "legacyType": "demo",
    "legacyPath": "legacy/prototype-v1/demos/匀变速直线运动演示器",
    "legacyTitle": "匀变速直线运动演示器",
    "targetSubject": "physics",
    "targetModule": "motion",
    "targetUnitSlug": "physics-accelerated-motion",
    "action": "rewrite-demo",
    "status": "planned",
    "priority": "high",
    "notes": "旧演示器重写为正式 DemoDefinition，目标单元：匀变速直线运动与图像。"
  },
  {
    "legacyType": "unit",
    "legacyPath": "legacy/prototype-v1/modules/unit-physics-accelerated-motion.html",
    "legacyTitle": "匀变速直线运动与图像",
    "targetSubject": "physics",
    "targetModule": "motion",
    "targetUnitSlug": "physics-accelerated-motion",
    "action": "migrate-as-is",
    "status": "planned",
    "priority": "high",
    "notes": "迁入正式知识点页，并按价值补交互 demo。"
  },
  {
    "legacyType": "demo",
    "legacyPath": "legacy/prototype-v1/demos/自由落体演示器",
    "legacyTitle": "自由落体演示器",
    "targetSubject": "physics",
    "targetModule": "motion",
    "targetUnitSlug": "physics-free-fall",
    "action": "rewrite-demo",
    "status": "planned",
    "priority": "medium",
    "notes": "旧演示器重写为正式 DemoDefinition，目标单元：自由落体。"
  },
  {
    "legacyType": "unit",
    "legacyPath": "legacy/prototype-v1/modules/unit-physics-free-fall.html",
    "legacyTitle": "自由落体",
    "targetSubject": "physics",
    "targetModule": "motion",
    "targetUnitSlug": "physics-free-fall",
    "action": "migrate-as-is",
    "status": "planned",
    "priority": "medium",
    "notes": "迁入正式知识点页，并按价值补交互 demo。"
  },
  {
    "legacyType": "demo",
    "legacyPath": "legacy/prototype-v1/demos/匀速与匀变速追及演示器",
    "legacyTitle": "匀速与匀变速追及演示器",
    "targetSubject": "physics",
    "targetModule": "motion",
    "targetUnitSlug": "physics-mixed-chase",
    "action": "rewrite-demo",
    "status": "planned",
    "priority": "medium",
    "notes": "旧演示器重写为正式 DemoDefinition，目标单元：匀速与匀变速追及。"
  },
  {
    "legacyType": "unit",
    "legacyPath": "legacy/prototype-v1/modules/unit-physics-mixed-chase.html",
    "legacyTitle": "匀速与匀变速追及",
    "targetSubject": "physics",
    "targetModule": "motion",
    "targetUnitSlug": "physics-mixed-chase",
    "action": "migrate-as-is",
    "status": "planned",
    "priority": "medium",
    "notes": "迁入正式知识点页，并按价值补交互 demo。"
  },
  {
    "legacyType": "demo",
    "legacyPath": "legacy/prototype-v1/demos/运动图像综合判读演示器",
    "legacyTitle": "运动图像综合判读演示器",
    "targetSubject": "physics",
    "targetModule": "motion",
    "targetUnitSlug": "physics-motion-graphs",
    "action": "rewrite-demo",
    "status": "planned",
    "priority": "medium",
    "notes": "旧演示器重写为正式 DemoDefinition，目标单元：运动图像综合判读。"
  },
  {
    "legacyType": "unit",
    "legacyPath": "legacy/prototype-v1/modules/unit-physics-motion-graphs.html",
    "legacyTitle": "运动图像综合判读",
    "targetSubject": "physics",
    "targetModule": "motion",
    "targetUnitSlug": "physics-motion-graphs",
    "action": "migrate-as-is",
    "status": "planned",
    "priority": "medium",
    "notes": "迁入正式知识点页，并按价值补交互 demo。"
  },
  {
    "legacyType": "demo",
    "legacyPath": "legacy/prototype-v1/demos/平抛运动演示器",
    "legacyTitle": "平抛运动演示器",
    "targetSubject": "physics",
    "targetModule": "motion",
    "targetUnitSlug": "physics-projectile-motion",
    "action": "rewrite-demo",
    "status": "planned",
    "priority": "medium",
    "notes": "旧演示器重写为正式 DemoDefinition，目标单元：平抛运动。"
  },
  {
    "legacyType": "unit",
    "legacyPath": "legacy/prototype-v1/modules/unit-physics-projectile-motion.html",
    "legacyTitle": "平抛运动",
    "targetSubject": "physics",
    "targetModule": "motion",
    "targetUnitSlug": "physics-projectile-motion",
    "action": "migrate-as-is",
    "status": "planned",
    "priority": "medium",
    "notes": "迁入正式知识点页，并按价值补交互 demo。"
  },
  {
    "legacyType": "demo",
    "legacyPath": "legacy/prototype-v1/demos/两车匀速追及演示器",
    "legacyTitle": "两车匀速追及演示器",
    "targetSubject": "physics",
    "targetModule": "motion",
    "targetUnitSlug": "physics-uniform-chase",
    "action": "rewrite-demo",
    "status": "planned",
    "priority": "medium",
    "notes": "旧演示器重写为正式 DemoDefinition，目标单元：两车匀速追及。"
  },
  {
    "legacyType": "unit",
    "legacyPath": "legacy/prototype-v1/modules/unit-physics-uniform-chase.html",
    "legacyTitle": "两车匀速追及",
    "targetSubject": "physics",
    "targetModule": "motion",
    "targetUnitSlug": "physics-uniform-chase",
    "action": "migrate-as-is",
    "status": "planned",
    "priority": "medium",
    "notes": "迁入正式知识点页，并按价值补交互 demo。"
  },
  {
    "legacyType": "demo",
    "legacyPath": "legacy/prototype-v1/demos/匀速直线运动演示器",
    "legacyTitle": "匀速直线运动演示器",
    "targetSubject": "physics",
    "targetModule": "motion",
    "targetUnitSlug": "physics-uniform-motion",
    "action": "rewrite-demo",
    "status": "planned",
    "priority": "high",
    "notes": "旧演示器重写为正式 DemoDefinition，目标单元：匀速直线运动与图像。"
  },
  {
    "legacyType": "unit",
    "legacyPath": "legacy/prototype-v1/modules/unit-physics-uniform-motion.html",
    "legacyTitle": "匀速直线运动与图像",
    "targetSubject": "physics",
    "targetModule": "motion",
    "targetUnitSlug": "physics-uniform-motion",
    "action": "migrate-as-is",
    "status": "planned",
    "priority": "high",
    "notes": "迁入正式知识点页，并按价值补交互 demo。"
  },
  {
    "legacyType": "module",
    "legacyPath": "legacy/prototype-v1/modules/physics-wave.html",
    "legacyTitle": "振动与波动",
    "targetSubject": "physics",
    "targetModule": "wave",
    "targetUnitSlug": null,
    "action": "migrate-as-is",
    "status": "planned",
    "priority": "high",
    "notes": "保留模块主线，迁入新站正式模块页。"
  },
  {
    "legacyType": "unit",
    "legacyPath": "legacy/prototype-v1/modules/unit-physics-vibration.html",
    "legacyTitle": "简谐振动的周期与图像",
    "targetSubject": "physics",
    "targetModule": "wave",
    "targetUnitSlug": "physics-vibration",
    "action": "migrate-as-is",
    "status": "planned",
    "priority": "medium",
    "notes": "迁入正式知识点页，并按价值补交互 demo。"
  },
  {
    "legacyType": "unit",
    "legacyPath": "legacy/prototype-v1/modules/unit-physics-wave-propagation.html",
    "legacyTitle": "波的传播与相位感知",
    "targetSubject": "physics",
    "targetModule": "wave",
    "targetUnitSlug": "physics-wave-propagation",
    "action": "migrate-as-is",
    "status": "planned",
    "priority": "medium",
    "notes": "迁入正式知识点页，并按价值补交互 demo。"
  }
];

export function getManifestBySubject(subjectId: MigrationManifestRecord["targetSubject"]) {
  return migrationManifest.filter((record) => record.targetSubject === subjectId);
}

export function getManifestByLegacyType(legacyType: MigrationManifestRecord["legacyType"]) {
  return migrationManifest.filter((record) => record.legacyType === legacyType);
}
