export const config = {
  id: "chemistry-sodium-demo",
  title: "钠及其化合物演示器",
  eyebrow: "元素化合物 · 钠",
  heroText: "把金属钠、氧化钠、过氧化钠、氢氧化钠放进同一条转化链里，让孩子把性质、现象和用途一起记住。",
  graphTitle: "钠系物质转化链",
  graphNote: "先看当前高亮场景，再回头看整条链，孩子会更容易从“零散物质”升级到“系统转化”。",
  controlTitle: "场景切换",
  controlHint: "先看反应对象，再讲现象",
  sampleTitle: "典型样例",
  sampleHint: "先看钠与水，再看燃烧与过氧化物用途",
  teachingTitle: "观察提示",
  teachingHint: "每次都把现象挂回转化链",
  backHref: "../../modules/unit-chemistry-sodium.html",
  backLabel: "返回钠及其化合物单元",
  controls: [
    {
      key: "sceneId",
      label: "当前场景",
      type: "select",
      default: "sodium-water",
      options: [
        { value: "sodium-water", label: "钠与水" },
        { value: "sodium-oxygen", label: "钠与氧气" },
        { value: "peroxide-carbon-dioxide", label: "过氧化钠与二氧化碳" },
      ],
    },
  ],
  presets: [
    { id: "water", label: "钠与水", params: { sceneId: "sodium-water" }, note: "先抓最有现象感的场景，最容易打开孩子的兴趣。" },
    { id: "oxygen", label: "钠与氧气", params: { sceneId: "sodium-oxygen" }, note: "讲条件变化时，最适合提醒 Na2O 与 Na2O2 不能混记。" },
    { id: "peroxide", label: "过氧化物用途", params: { sceneId: "peroxide-carbon-dioxide" }, note: "把性质和用途连在一起，孩子更容易形成稳定记忆。" },
  ],
  viewport: { xMin: 0, xMax: 12, yMin: 0, yMax: 8 },
  features: { animation: true, gridToggle: false, keyPointToggle: false, explanationCards: true },
  initialMessage: "先问孩子：这些物质为什么不该被分开死记，而应该放在一条链上看？",
  liveMessage: "钠这一章最值得抓住的是“转化链 + 现象 + 用途”三线合一。",
  resetMessage: "已经回到钠与水的基础场景。",
};
