export const config = {
  id: "sin-transform-demo",
  title: "三角函数参数演示器",
  eyebrow: "三角函数 · 参数变化",
  heroText: "把振幅、周期、相位和平移的影响拆开看，三角函数就不会混成一团。",
  graphTitle: "参数变化舞台",
  graphNote: "先看振幅和周期，再看相位和平移。",
  controlHint: "推荐按 A → ω → φ → d 的顺序观察",
  sampleHint: "常见波形一键切换",
  teachingHint: "先盯住中线和周期",
  controls: [
    { key: "amplitude", label: "振幅 A", type: "range", min: 0.5, max: 3, step: 0.1, default: 1 },
    { key: "omega", label: "角速度 ω", type: "range", min: 0.5, max: 3, step: 0.1, default: 1 },
    { key: "phase", label: "相位 φ", type: "range", min: -3.141592653589793, max: 3.141592653589793, step: 0.1, default: 0 },
    { key: "offset", label: "上下平移 d", type: "range", min: -3, max: 3, step: 0.1, default: 0 },
  ],
  presets: [
    { id: "standard", label: "标准波形", params: { amplitude: 1, omega: 1, phase: 0, offset: 0 }, note: "先把标准 sin(x) 看熟，再去看参数变化。" },
    { id: "amplitude", label: "振幅放大", params: { amplitude: 2.2, omega: 1, phase: 0, offset: 0 }, note: "A 变大以后，波峰更高、波谷更低。" },
    { id: "period", label: "周期压缩", params: { amplitude: 1, omega: 2, phase: 0, offset: 0 }, note: "ω 变大以后，一个周期会变短，波形更密。" },
    { id: "phase", label: "向右平移", params: { amplitude: 1, omega: 1, phase: -Math.PI / 2, offset: 0 }, note: "φ 改变以后，整条曲线会左右平移。" },
    { id: "offset", label: "整体上移", params: { amplitude: 1, omega: 1, phase: 0, offset: 1.5 }, note: "d 决定整条曲线的中线上移还是下移。" },
  ],
  viewport: { xMin: 0, xMax: Math.PI * 4, yMin: -4, yMax: 4 },
  features: { animation: true, gridToggle: true, keyPointToggle: true, explanationCards: true },
  initialMessage: "先看标准波形，再把四个参数一个一个拆开。",
  liveMessage: "看三角函数参数变化时，最稳的抓手是振幅、周期和中线。",
  resetMessage: "已经回到最标准的正弦波形。",
};
