export const config = {
  id: "english-clause-hierarchy-demo",
  title: "从句层级演示器",
  eyebrow: "英语语法 · 从句层级",
  heroText: "把主句、从句、连接词和句法作用拆成层级结构，让孩子先看清从句在整句里充当什么，再记名称。",
  graphTitle: "从句层级观察舞台",
  graphNote: "先问从句回答了整句里的什么问题，再看它挂在谁身上，判断会比死背定义更稳。",
  controlTitle: "从句切换",
  controlHint: "先问功能，再记名称",
  sampleTitle: "典型样例",
  sampleHint: "先看宾语从句，再看状语从句",
  teachingTitle: "观察提示",
  teachingHint: "每次都先找它充当什么成分",
  backHref: "../../modules/unit-english-clause-hierarchy.html",
  backLabel: "返回从句层级拆解单元",
  controls: [
    {
      key: "clauseId",
      label: "当前从句",
      type: "select",
      default: "noun-clause",
      options: [
        { value: "noun-clause", label: "宾语从句" },
        { value: "adverbial-clause", label: "状语从句" },
      ],
    },
    {
      key: "focusClause",
      label: "聚焦节点",
      type: "select",
      default: "object-clause",
      options: [
        { value: "object-clause", label: "从句主体" },
        { value: "adverbial-clause", label: "状语从句" },
        { value: "main-predicate", label: "主句谓语" },
        { value: "linker", label: "连接词" },
      ],
    },
  ],
  presets: [
    { id: "noun", label: "宾语从句", params: { clauseId: "noun-clause", focusClause: "object-clause" }, note: "最适合先建立“这个从句在回答什么问题”的判断意识。" },
    { id: "adverbial", label: "状语从句", params: { clauseId: "adverbial-clause", focusClause: "adverbial-clause" }, note: "切到状语从句时，更容易看出它是在补充时间、条件或原因。" },
  ],
  viewport: { xMin: 0, xMax: 12, yMin: 0, yMax: 8 },
  features: { animation: true, gridToggle: false, keyPointToggle: false, explanationCards: true },
  initialMessage: "先问：这个从句在整句里到底相当于什么成分？",
  liveMessage: "从句判断的关键不是名字，而是功能位置。",
  resetMessage: "已经回到宾语从句样例。",
};
