export const config = {
  id: "physics-mixed-chase-demo",
  title: "匀速与匀变速追及演示器",
  eyebrow: "物理运动学 · 匀速与匀变速追及",
  heroText: "把前车匀速、后车加速和追及交点放进同一张 s-t 图像里，让孩子看懂“后车一开始不快，为什么后来仍能追上”。",
  graphTitle: "混合追及位移-时间图像",
  graphNote: "蓝线表示前车匀速直线，绿线表示后车加速曲线。交点表示同一时刻位置相同，也就是现实中的追上。",
  controlHint: "推荐按 后车加速度 → 后车初速度 → 前车速度 → 两车起点 → 观察时刻 的顺序观察",
  sampleHint: "先看 4 种典型混合追及情境",
  teachingHint: "先判断有没有交点，再解释为什么后来能追上",
  backHref: "../../modules/unit-physics-mixed-chase.html",
  backLabel: "返回匀速与匀变速追及单元",
  controls: [
    { key: "leadStart", label: "前车起点 sA0", type: "range", min: 2, max: 14, step: 0.5, default: 8 },
    { key: "leadSpeed", label: "前车速度 vA", type: "range", min: 0.5, max: 4, step: 0.1, default: 2 },
    { key: "chaseStart", label: "后车起点 sB0", type: "range", min: -6, max: 6, step: 0.5, default: 0 },
    { key: "chaseInitialSpeed", label: "后车初速度 vB0", type: "range", min: 0, max: 4, step: 0.1, default: 0 },
    { key: "chaseAcceleration", label: "后车加速度 aB", type: "range", min: 0, max: 3, step: 0.1, default: 2 },
    { key: "t", label: "观察时刻 t", type: "range", min: 0, max: 10, step: 0.2, default: 3 },
  ],
  presets: [
    { id: "eventual-catch", label: "先慢后追上", params: { leadStart: 8, leadSpeed: 2, chaseStart: 0, chaseInitialSpeed: 0, chaseAcceleration: 2, t: 3 }, note: "后车一开始速度不大，但因为持续加速，曲线最终还是会与前车直线相交。" },
    { id: "quick-catch", label: "较快追上", params: { leadStart: 6, leadSpeed: 1.5, chaseStart: 0, chaseInitialSpeed: 1.5, chaseAcceleration: 2.4, t: 2.5 }, note: "后车初速度本来就不低，再叠加加速度，追上会来得更早。" },
    { id: "late-catch", label: "起点差大但能追上", params: { leadStart: 12, leadSpeed: 2, chaseStart: -2, chaseInitialSpeed: 0.5, chaseAcceleration: 2.6, t: 4 }, note: "虽然起点差很大，但只要后车持续加速足够明显，后面依然可能追上。" },
    { id: "no-catch-yet", label: "暂时追不上", params: { leadStart: 10, leadSpeed: 3, chaseStart: 0, chaseInitialSpeed: 0.2, chaseAcceleration: 0.4, t: 5 }, note: "加速太小的时候，后车曲线抬升不够快，在当前模型中就看不到交点。" },
  ],
  viewport: { xMin: 0, xMax: 10, yMin: -6, yMax: 22 },
  features: { animation: true, gridToggle: true, keyPointToggle: true, explanationCards: true },
  initialMessage: "准备好了，先固定起点差，只改后车加速度，看绿线什么时候开始明显弯起来。",
  liveMessage: "混合追及里最值得观察的是：后车不是一直更快，但它会不会越来越快到足以追上。",
  resetMessage: "已经回到最基础的匀速与匀变速追及模型。",
};
