export const config = {
  id: "physics-motion-graphs-demo",
  title: "运动图像综合判读演示器",
  eyebrow: "物理运动学 · 图像综合判读",
  heroText: "把同一个匀变速过程同时投到 s-t 图像和 v-t 图像上，让孩子学会在两张图之间来回翻译物理过程。",
  graphTitle: "s-t / v-t 联动图像",
  graphNote: "蓝线是 s-t 图像，紫线是 v-t 图像。当前时刻在两张图上的对应点会同步高亮。",
  controlHint: "推荐按 加速度 → 初速度 → 观察时刻 的顺序观察",
  sampleHint: "先看 4 种典型图像组合",
  teachingHint: "先说出每张图各自回答什么问题",
  backHref: "../../modules/unit-physics-motion-graphs.html",
  backLabel: "返回运动图像综合判读单元",
  controls: [
    { key: "v0", label: "初速度 v0", type: "range", min: -2, max: 6, step: 0.2, default: 2 },
    { key: "a", label: "加速度 a", type: "range", min: -2, max: 3, step: 0.1, default: 1 },
    { key: "t", label: "观察时刻 t", type: "range", min: 0, max: 6, step: 0.1, default: 3 },
  ],
  presets: [
    { id: "speed-up", label: "加速前进", params: { v0: 2, a: 1, t: 3 }, note: "v-t 是上升直线，s-t 会越来越陡，说明速度在逐步变大。" },
    { id: "uniform", label: "匀速前进", params: { v0: 3, a: 0, t: 3 }, note: "v-t 是水平线，s-t 是斜直线，说明速度不变、位置稳定增加。" },
    { id: "slow-down", label: "减速前进", params: { v0: 5, a: -1, t: 3 }, note: "v-t 向下倾斜，s-t 虽然还在上升，但会越来越平，说明物体还在前进只是越来越慢。" },
    { id: "reverse-risk", label: "可能反向", params: { v0: 1, a: -1.2, t: 3 }, note: "v-t 会穿过 0，这表示物体可能先停下再反向；只看 s-t 的“高低”容易误判。" },
  ],
  viewport: { xMin: 0, xMax: 6, yMin: -4, yMax: 14 },
  features: { animation: true, gridToggle: true, keyPointToggle: true, explanationCards: true },
  initialMessage: "准备好了，先固定一个时刻，只改加速度，看 s-t 和 v-t 图像各自怎么变。",
  liveMessage: "图像综合题里，先分清 s-t 在说位置，v-t 在说速度，会少很多误判。",
  resetMessage: "已经回到最基础的图像综合场景。",
};
