export const config = {
  id: "point-line-distance-demo",
  title: "点到直线距离演示器",
  eyebrow: "解析几何 · 距离模型",
  heroText: "把点、直线、垂足和最短线段一起画出来，让孩子先看懂为什么最短距离一定沿着垂线段。",
  graphTitle: "点、直线与垂足",
  graphNote: "橙色线段就是最短距离，终点一定落在垂足上。",
  controlHint: "先调点的位置，再调直线",
  sampleHint: "先把垂足看熟，再看距离变化",
  teachingHint: "先找垂线段，再读距离",
  controls: [
    { key: "x0", label: "点横坐标 x0", type: "range", min: -5, max: 5, step: 0.2, default: 0 },
    { key: "y0", label: "点纵坐标 y0", type: "range", min: -5, max: 5, step: 0.2, default: 3 },
    { key: "k", label: "斜率 k", type: "range", min: -3, max: 3, step: 0.1, default: 1 },
    { key: "b", label: "截距 b", type: "range", min: -4, max: 4, step: 0.2, default: 0 },
  ],
  presets: [
    { id: "basic", label: "基础垂足", params: { x0: 0, y0: 3, k: 1, b: 0 }, note: "先看最标准的一组，先把垂足和最短线段看清楚。" },
    { id: "negative-slope", label: "负斜率直线", params: { x0: 2, y0: 3, k: -1, b: 1 }, note: "直线方向一变，垂足位置也会跟着明显变化。" },
    { id: "point-below", label: "点在下方", params: { x0: -2, y0: -3, k: 0.5, b: 1 }, note: "点跑到直线下方时，最短线段还是垂线段。" },
    { id: "far-away", label: "远离直线", params: { x0: 4, y0: 4, k: 0, b: -1 }, note: "点离直线越远，橙色最短线段会直接变长。" },
  ],
  viewport: { xMin: -6, xMax: 6, yMin: -6, yMax: 6 },
  features: { animation: true, gridToggle: true, keyPointToggle: true, explanationCards: true },
  initialMessage: "准备好了，先盯住垂足的位置。",
  liveMessage: "先看哪条线段和直线垂直，再看它为什么恰好最短。",
  resetMessage: "已经回到最基础的点到直线距离模型。",
};
