export const config = {
  id: "english-nonfinite-structure-demo",
  title: "非谓语结构演示器",
  eyebrow: "英语语法 · 非谓语结构",
  heroText: "把不定式和分词挂回主句结构里，让孩子看清它们不是主干动作，而是在补充目的、伴随或背景信息。",
  graphTitle: "非谓语结构观察舞台",
  graphNote: "先找主句，再看非谓语结构挂在谁身上、在补哪一层信息。",
  controlTitle: "结构切换",
  controlHint: "先分主干和附着层",
  sampleTitle: "典型样例",
  sampleHint: "先看不定式目的，再看分词伴随",
  teachingTitle: "观察提示",
  teachingHint: "每次先问它是不是主干动作",
  backHref: "../../modules/unit-english-nonfinite-structure.html",
  backLabel: "返回非谓语结构关系图单元",
  controls: [
    {
      key: "patternId",
      label: "当前结构",
      type: "select",
      default: "to-learn-purpose",
      options: [
        { value: "to-learn-purpose", label: "不定式作目的" },
        { value: "walking-companion", label: "分词作伴随" },
      ],
    },
    {
      key: "focusNodeId",
      label: "聚焦节点",
      type: "select",
      default: "infinitive",
      options: [
        { value: "infinitive", label: "不定式" },
        { value: "participle", label: "分词结构" },
        { value: "main-predicate", label: "主句动作" },
        { value: "purpose", label: "目的层" },
        { value: "companion", label: "伴随层" },
      ],
    },
  ],
  presets: [
    { id: "purpose", label: "目的不定式", params: { patternId: "to-learn-purpose", focusNodeId: "infinitive" }, note: "最适合先建立“to do 不一定是主句动作”的意识。" },
    { id: "participle", label: "伴随分词", params: { patternId: "walking-companion", focusNodeId: "participle" }, note: "帮助孩子看懂分词结构常常只是背景或伴随信息。" },
  ],
  viewport: { xMin: 0, xMax: 12, yMin: 0, yMax: 8 },
  features: { animation: true, gridToggle: false, keyPointToggle: false, explanationCards: true },
  initialMessage: "先问自己：这个结构是不是主句真正发生的动作？",
  liveMessage: "非谓语越能放回主句结构，复杂句就越不容易乱。",
  resetMessage: "已经回到不定式作目的样例。",
};
