export const config = {
  id: "english-writing-upgrade-workshop-demo",
  title: "写作升级工坊演示器",
  eyebrow: "英语写作 · 句型升级",
  heroText: "把基础句一步步升级成更清楚、更自然的书面表达，让孩子看清句式提升路径。",
  graphTitle: "写作升级观察舞台",
  graphNote: "先看基础句的问题在哪里，再看结构怎么改，最后再看升级后为什么更好。",
  controlTitle: "升级样例切换",
  controlHint: "先找基础句，再看升级路径",
  sampleTitle: "典型样例",
  sampleHint: "先看 because 句，再看 if 句",
  teachingTitle: "观察提示",
  teachingHint: "每次先说基础句哪里还能更好",
  backHref: "../../modules/unit-english-writing-upgrade-workshop.html",
  backLabel: "返回写作句型升级工坊单元",
  controls: [
    {
      key: "patternId",
      label: "当前样例",
      type: "select",
      default: "because-upgrade",
      options: [
        { value: "because-upgrade", label: "原因句升级" },
        { value: "if-upgrade", label: "条件句升级" },
      ],
    },
    {
      key: "focusStage",
      label: "聚焦阶段",
      type: "select",
      default: "advanced",
      options: [
        { value: "basic", label: "基础表达" },
        { value: "link", label: "改造节点" },
        { value: "advanced", label: "升级表达" },
        { value: "effect", label: "表达效果" },
      ],
    },
  ],
  presets: [
    { id: "because", label: "原因句升级", params: { patternId: "because-upgrade", focusStage: "advanced" }, note: "最适合先让孩子看见基础句如何自然升级成更清楚的书面表达。" },
    { id: "if", label: "条件句升级", params: { patternId: "if-upgrade", focusStage: "effect" }, note: "帮助孩子把条件句从“会写”推进到“写得更像作文”。" },
  ],
  viewport: { xMin: 0, xMax: 12, yMin: 0, yMax: 8 },
  features: { animation: true, gridToggle: false, keyPointToggle: false, explanationCards: true },
  initialMessage: "先问自己：这句虽然没错，但哪里还能写得更清楚、更自然？",
  liveMessage: "写作升级先看结构升级，再谈词汇华丽。",
  resetMessage: "已经回到原因句升级样例。",
};
