export const config = {
  id: "tan-basic-demo",
  title: "正切函数演示器",
  eyebrow: "三角函数 · tan(x) 与间断",
  heroText: "让孩子直观看到渐近线、分段变化和周期，建立对正切函数的连续感。",
  graphTitle: "正切图像舞台",
  graphNote: "重点盯住渐近线、周期和中线位置。",
  controlHint: "先看标准图像，再观察 ω、φ、d 的影响",
  sampleHint: "典型变化一键切换",
  teachingHint: "渐近线附近最值得观察",
  controls: [
    { key: "omega", label: "角速度 ω", type: "range", min: 0.5, max: 2.5, step: 0.1, default: 1 },
    { key: "phase", label: "相位 φ", type: "range", min: -1.5707963267948966, max: 1.5707963267948966, step: 0.1, default: 0 },
    { key: "offset", label: "上下平移 d", type: "range", min: -3, max: 3, step: 0.1, default: 0 },
  ],
  presets: [
    { id: "standard", label: "标准正切", params: { omega: 1, phase: 0, offset: 0 }, note: "先看最标准的 tan(x)，重点是渐近线和周期。" },
    { id: "compress", label: "周期变短", params: { omega: 2, phase: 0, offset: 0 }, note: "ω 变大以后，一个周期会缩短，图像会更密。" },
    { id: "shift", label: "相位平移", params: { omega: 1, phase: Math.PI / 4, offset: 0 }, note: "φ 改变以后，整组分段都会一起左右平移。" },
    { id: "up", label: "整体上移", params: { omega: 1, phase: 0, offset: 1.2 }, note: "d 决定整条函数的中线会上移还是下移。" },
  ],
  viewport: { xMin: -Math.PI, xMax: Math.PI, yMin: -5, yMax: 5 },
  features: { animation: true, gridToggle: true, keyPointToggle: true, explanationCards: true },
  initialMessage: "先认清渐近线在哪，再看曲线怎样一段一段变化。",
  liveMessage: "正切函数最值得先看的是渐近线、周期和中线。",
  resetMessage: "已经回到标准正切函数。",
};
