export const config = {
  id: "chemistry-iron-demo",
  title: "铁及其化合物演示器",
  eyebrow: "元素化合物 · 铁",
  heroText: "把铁、亚铁、铁离子的价态变化、颜色线索和检验方法放进一条连续变化链，让孩子减少碎片记忆。",
  graphTitle: "铁系价态转化链",
  graphNote: "先看当前场景的价态起点和终点，再用颜色和检验标签把记忆钉住，最后回到整条铁系主线。",
  controlTitle: "场景切换",
  controlHint: "先认价态，再看检验",
  sampleTitle: "典型样例",
  sampleHint: "先看亚铁变铁，再看还原和金属铁入链",
  teachingTitle: "观察提示",
  teachingHint: "价态、颜色、检验三线合一",
  backHref: "../../modules/unit-chemistry-iron.html",
  backLabel: "返回铁及其化合物单元",
  controls: [
    {
      key: "sceneId",
      label: "当前场景",
      type: "select",
      default: "ferrous-to-ferric",
      options: [
        { value: "ferrous-to-ferric", label: "Fe2+ -> Fe3+" },
        { value: "ferric-to-ferrous", label: "Fe3+ -> Fe2+" },
        { value: "iron-metal-to-ferrous", label: "Fe -> Fe2+" },
      ],
    },
  ],
  presets: [
    { id: "oxidation", label: "亚铁被氧化", params: { sceneId: "ferrous-to-ferric" }, note: "最适合先建立浅绿色 Fe2+ 与黄色 Fe3+ 的对比。" },
    { id: "reduction", label: "铁离子被还原", params: { sceneId: "ferric-to-ferrous" }, note: "讲可逆变化时，更容易让孩子理解价态不是孤立结论。" },
    { id: "metal", label: "金属铁入链", params: { sceneId: "iron-metal-to-ferrous" }, note: "把铁单质也并入主链，整章会更完整。" },
  ],
  viewport: { xMin: 0, xMax: 12, yMin: 0, yMax: 8 },
  features: { animation: true, gridToggle: false, keyPointToggle: false, explanationCards: true },
  initialMessage: "先问孩子：现在是哪一种铁的状态，它下一步会变成谁？",
  liveMessage: "铁这一章最关键的是把价态、颜色和检验一起记。",
  resetMessage: "已经回到亚铁被氧化的基础场景。",
};
