export const config = {
  id: "english-grammar-cloze-strategy-demo",
  title: "语法填空策略演示器",
  eyebrow: "英语语法 · 填空策略",
  heroText: "把语法填空的空格判断、句法分析和形式选择拆成路径图，让孩子做题时不再凭感觉乱猜。",
  graphTitle: "语法填空观察舞台",
  graphNote: "先判断空格在句子里做什么，再决定填什么形式，不要一眼直接猜答案。",
  controlTitle: "题型切换",
  controlHint: "先看功能，再选形式",
  sampleTitle: "典型样例",
  sampleHint: "先看动词形式题，再看词形变化题",
  teachingTitle: "观察提示",
  teachingHint: "每次先说空格在句子里做什么",
  backHref: "../../modules/unit-english-grammar-cloze-strategy.html",
  backLabel: "返回语法填空策略演示器单元",
  controls: [
    {
      key: "taskId",
      label: "当前题型",
      type: "select",
      default: "verb-form",
      options: [
        { value: "verb-form", label: "动词形式题" },
        { value: "word-class", label: "词形变化题" },
      ],
    },
    {
      key: "focusNodeId",
      label: "聚焦步骤",
      type: "select",
      default: "syntax",
      options: [
        { value: "blank", label: "空格位置" },
        { value: "syntax", label: "句法判断" },
        { value: "tense", label: "形式判断" },
        { value: "answer", label: "确定答案" },
      ],
    },
  ],
  presets: [
    { id: "verb", label: "动词形式题", params: { taskId: "verb-form", focusNodeId: "syntax" }, note: "最适合先让孩子看懂动词题不能跳过谓语和非谓语判断。" },
    { id: "class", label: "词形变化题", params: { taskId: "word-class", focusNodeId: "tense" }, note: "帮助孩子把词性判断和固定搭配拆成两个清楚步骤。" },
  ],
  viewport: { xMin: 0, xMax: 12, yMin: 0, yMax: 8 },
  features: { animation: true, gridToggle: false, keyPointToggle: false, explanationCards: true },
  initialMessage: "先让孩子回答：这个空格在句子里到底在做什么？",
  liveMessage: "语法填空先定功能，再选形式，路径越清楚越稳。",
  resetMessage: "已经回到动词形式题样例。",
};
