export const config = {
  id: "english-reading-layer-demo",
  title: "阅读分层演示器",
  eyebrow: "英语阅读 · 信息分层",
  heroText: "把一篇短文先拆成主旨、理由、细节和例子，让孩子读文章时先抓重点，再看支撑信息。",
  graphTitle: "阅读层级观察舞台",
  graphNote: "先问这篇短文最想表达什么，再看哪些句子是在解释、举例或补数据。",
  controlTitle: "短文切换",
  controlHint: "先抓主旨，再看支撑层",
  sampleTitle: "典型样例",
  sampleHint: "先看 solar 项目，再看阅读社团",
  teachingTitle: "观察提示",
  teachingHint: "每次先说中心，再分支撑",
  backHref: "../../modules/unit-english-reading-layer.html",
  backLabel: "返回阅读信息分层单元",
  controls: [
    {
      key: "passageId",
      label: "当前短文",
      type: "select",
      default: "solar-school",
      options: [
        { value: "solar-school", label: "校园太阳能短文" },
        { value: "library-club", label: "阅读社团短文" },
      ],
    },
    {
      key: "emphasis",
      label: "聚焦层",
      type: "select",
      default: "main-idea",
      options: [
        { value: "main-idea", label: "主旨" },
        { value: "reason-1", label: "理由 1" },
        { value: "reason-2", label: "理由 2 / 做法 2" },
        { value: "detail", label: "细节" },
        { value: "example", label: "例子" },
        { value: "effect", label: "效果" },
      ],
    },
  ],
  presets: [
    { id: "idea", label: "先抓主旨", params: { passageId: "solar-school", emphasis: "main-idea" }, note: "最适合先建立“短文先抓中心意思”的动作意识。" },
    { id: "detail", label: "看支撑层", params: { passageId: "library-club", emphasis: "effect" }, note: "帮助孩子分清主旨、做法和结果不是一个层级。" },
  ],
  viewport: { xMin: 0, xMax: 12, yMin: 0, yMax: 8 },
  features: { animation: true, gridToggle: false, keyPointToggle: false, explanationCards: true },
  initialMessage: "先问自己：这篇短文如果只能留一句，最核心的意思是什么？",
  liveMessage: "阅读分层越清楚，主旨题和细节题就越不容易混。",
  resetMessage: "已经回到校园太阳能短文样例。",
};
