export const config = {
  id: "chemistry-ion-identification-demo",
  title: "离子检验演示器",
  eyebrow: "化学实验与现象 · 离子检验",
  heroText: "把离子检验从“背现象”拉回“按步骤判断”，让孩子看到试剂、现象、排除和结论是怎样串起来的。",
  graphTitle: "离子检验判断链",
  graphNote: "左边是试剂与条件，中间是观察现象，右边是结论，底部则提醒为什么要做排除。",
  controlTitle: "检验条件",
  controlHint: "先选离子，再看排除链",
  sampleTitle: "典型样例",
  sampleHint: "先做氯离子，再扩到硫酸根和铵根",
  teachingTitle: "观察提示",
  teachingHint: "每次都按“试剂-现象-排除-结论”讲",
  backHref: "../../modules/unit-chemistry-ion-identification.html",
  backLabel: "返回离子检验单元",
  controls: [
    {
      key: "ionId",
      label: "待检离子",
      type: "select",
      default: "chloride",
      options: [
        { value: "chloride", label: "Cl-" },
        { value: "sulfate", label: "SO4^2-" },
        { value: "ammonium", label: "NH4+" },
      ],
    },
    {
      key: "strictMode",
      label: "显示排除提醒",
      type: "toggle",
      default: true,
    },
  ],
  presets: [
    { id: "chloride", label: "氯离子", params: { ionId: "chloride", strictMode: true }, note: "最适合先建立“先酸化，再加 AgNO3”的步骤意识。" },
    { id: "sulfate", label: "硫酸根", params: { ionId: "sulfate", strictMode: true }, note: "适合讲“白色沉淀”也要看后续条件，不能只看表面现象。" },
    { id: "ammonium", label: "铵根", params: { ionId: "ammonium", strictMode: true }, note: "把气味、试纸变化和加热条件一起说出来，路径会更完整。" },
  ],
  viewport: { xMin: 0, xMax: 12, yMin: 0, yMax: 8 },
  features: { animation: true, gridToggle: false, keyPointToggle: false, explanationCards: true },
  initialMessage: "先让孩子按顺序复述：加什么、看到什么、排除什么、最后说明什么。",
  liveMessage: "离子检验真正要练的是判断链，而不是孤立现象。",
  resetMessage: "已经回到氯离子检验的基础场景。",
};
