export const config = {
  id: "line-circle-demo",
  title: "直线与圆位置关系演示器",
  eyebrow: "解析几何 · 直线与圆",
  heroText: "把“相交、相切、相离”从判别式和距离公式，变成孩子眼前真的在动的图形关系。",
  graphTitle: "直线与圆的关系",
  graphNote: "先看圆心到直线的距离，再看公共点个数，关系会一下子清楚。",
  controlHint: "推荐先调 b，再调 r",
  sampleHint: "先把三种基本关系看熟",
  teachingHint: "先看距离，再看交点",
  controls: [
    { key: "k", label: "斜率 k", type: "range", min: -3, max: 3, step: 0.1, default: 0.5 },
    { key: "b", label: "截距 b", type: "range", min: -5, max: 5, step: 0.2, default: 0 },
    { key: "cx", label: "圆心 x", type: "range", min: -4, max: 4, step: 0.2, default: 0 },
    { key: "cy", label: "圆心 y", type: "range", min: -4, max: 4, step: 0.2, default: 0 },
    { key: "r", label: "半径 r", type: "range", min: 1, max: 5, step: 0.2, default: 3 },
  ],
  presets: [
    { id: "secant", label: "标准相交", params: { k: 0.5, b: 0, cx: 0, cy: 0, r: 3 }, note: "先看相交，直线会穿过圆，出现两个交点。" },
    { id: "tangent", label: "水平相切", params: { k: 0, b: 3, cx: 0, cy: 0, r: 3 }, note: "当直线离圆心的距离刚好等于半径时，就会相切。" },
    { id: "separate", label: "整体相离", params: { k: 0, b: 4.2, cx: 0, cy: 0, r: 3 }, note: "当直线离圆心比半径还远时，就不会碰到圆。" },
    { id: "offset-circle", label: "偏心圆", params: { k: -0.6, b: 1.5, cx: 1.5, cy: -0.8, r: 2.4 }, note: "把圆心挪开以后，方程和图形的关系会更直观地显出来。" },
  ],
  viewport: { xMin: -8, xMax: 8, yMin: -8, yMax: 8 },
  features: { animation: true, gridToggle: true, keyPointToggle: true, explanationCards: true },
  initialMessage: "准备好了，建议先只拖截距 b 看关系切换。",
  liveMessage: "最稳的抓手不是判别式，而是“圆心到直线的距离”和“半径”的比较。",
  resetMessage: "已经回到最基础的直线与圆关系模型。",
};
