export const config = {
  id: "physics-projectile-motion-demo",
  title: "平抛运动演示器",
  eyebrow: "物理运动学 · 平抛运动",
  heroText: "把水平方向匀速、竖直方向自由落体和合成轨迹放到同一张图里，让孩子真正看懂平抛运动为什么一定要分方向看。",
  graphTitle: "平抛轨迹与分方向对应",
  graphNote: "蓝色曲线是平抛轨迹。当前点的横向位移和竖向高度会同步标出来，帮助孩子把两个方向重新对齐。",
  controlHint: "推荐按 初速度 → 初始高度 → 观察时刻 → 重力加速度 的顺序观察",
  sampleHint: "先看 4 种典型平抛场景",
  teachingHint: "先分别说出水平和竖直方向在做什么",
  backHref: "../../modules/unit-physics-projectile-motion.html",
  backLabel: "返回平抛运动单元",
  controls: [
    { key: "v0x", label: "水平初速度 v0x", type: "range", min: 2, max: 12, step: 0.2, default: 6 },
    { key: "h0", label: "初始高度 h0", type: "range", min: 5, max: 40, step: 1, default: 20 },
    { key: "g", label: "重力加速度 g", type: "range", min: 6, max: 12, step: 0.1, default: 10 },
    { key: "t", label: "观察时刻 t", type: "range", min: 0, max: 4, step: 0.05, default: 1 },
  ],
  presets: [
    { id: "basic", label: "基础平抛", params: { v0x: 6, h0: 20, g: 10, t: 1 }, note: "最基础的平抛情境里，横向位移稳定增长，竖向高度则按自由落体规律下降。" },
    { id: "high-platform", label: "高台平抛", params: { v0x: 5, h0: 32, g: 9.8, t: 1.6 }, note: "初始高度更大时，物体在空中的时间更长，也就有更长的水平射程。" },
    { id: "fast-throw", label: "更快抛出", params: { v0x: 10, h0: 18, g: 10, t: 1.2 }, note: "水平初速度更大时，单位时间里的水平位移更大，但竖直方向并不会因此改变。" },
    { id: "weaker-gravity", label: "重力较弱", params: { v0x: 7, h0: 20, g: 7.5, t: 1.4 }, note: "重力减小时，竖直下落变慢，所以同样时间内轨迹会更“平”。" },
  ],
  viewport: { xMin: 0, xMax: 14, yMin: -2, yMax: 24 },
  features: { animation: true, gridToggle: true, keyPointToggle: true, explanationCards: true },
  initialMessage: "准备好了，先固定一个时刻，只改水平初速度，看横向和竖向过程为什么必须分开看。",
  liveMessage: "平抛最关键的不是背两套公式，而是记住同一时刻里两个方向同时在发生什么。",
  resetMessage: "已经回到最基础的平抛模型。",
};
