export const config = {
  id: "english-reading-question-map-demo",
  title: "阅读题型拆解演示器",
  eyebrow: "英语阅读 · 题型路径",
  heroText: "把不同阅读题型拆成不同的定位和排除路径，让孩子做题时先分类型，再走流程。",
  graphTitle: "阅读题型观察舞台",
  graphNote: "先看题干要你找什么，再决定回原文找中心、找细节，还是排除干扰项。",
  controlTitle: "题型切换",
  controlHint: "先分题型，再走路径",
  sampleTitle: "典型样例",
  sampleHint: "先看主旨题，再看细节题",
  teachingTitle: "观察提示",
  teachingHint: "每次先说这是什么题型",
  backHref: "../../modules/unit-english-reading-question-map.html",
  backLabel: "返回阅读题型拆解演示器单元",
  controls: [
    {
      key: "questionId",
      label: "当前题型",
      type: "select",
      default: "main-idea",
      options: [
        { value: "main-idea", label: "主旨题" },
        { value: "detail", label: "细节题" },
      ],
    },
    {
      key: "focusNodeId",
      label: "聚焦步骤",
      type: "select",
      default: "evidence",
      options: [
        { value: "question", label: "题干识别" },
        { value: "article", label: "回全文" },
        { value: "keyword", label: "圈关键词" },
        { value: "evidence", label: "定位证据" },
        { value: "trap", label: "干扰项" },
        { value: "compare", label: "比选项" },
      ],
    },
  ],
  presets: [
    { id: "main", label: "主旨题", params: { questionId: "main-idea", focusNodeId: "evidence" }, note: "最适合先建立主旨题要回全文抓中心，而不是抠局部细节的意识。" },
    { id: "detail", label: "细节题", params: { questionId: "detail", focusNodeId: "compare" }, note: "帮助孩子看懂细节题要靠关键词回原文定位，不要靠印象。" },
  ],
  viewport: { xMin: 0, xMax: 12, yMin: 0, yMax: 8 },
  features: { animation: true, gridToggle: false, keyPointToggle: false, explanationCards: true },
  initialMessage: "先让孩子回答：这道题到底在问全文中心，还是在问具体细节？",
  liveMessage: "阅读题先分题型，再走路径，准确率会明显更稳。",
  resetMessage: "已经回到主旨题样例。",
};
