export const config = {
  id: "recursive-sequence-demo",
  title: "递推数列演示器",
  eyebrow: "数列主线 · 递推生成",
  heroText: "把“后一项由前一项推出来”的过程直接画出来，帮助孩子真正理解递推不是另一套死公式，而是一种生成规则。",
  graphTitle: "递推生成舞台",
  graphNote: "每个点都由前一个点推出来，先看生成过程，再回头看递推式。",
  controlHint: "先固定首项，再调乘数和常数项",
  sampleHint: "先看增长，再看稳定和衰减",
  teachingHint: "一项一项推出来",
  controls: [
    { key: "a1", label: "首项 a1", type: "range", min: 0, max: 4, step: 0.5, default: 1 },
    { key: "factor", label: "递推乘数 p", type: "range", min: 0.5, max: 2.5, step: 0.1, default: 2 },
    { key: "offset", label: "递推常数 q", type: "range", min: -2, max: 3, step: 0.5, default: 1 },
    { key: "count", label: "项数 n", type: "range", min: 5, max: 10, step: 1, default: 6 },
  ],
  presets: [
    { id: "fast-rise", label: "快速增长", params: { a1: 1, factor: 2, offset: 1, count: 6 }, note: "当后一项总是由前一项翻倍再加一点时，后面的增长会很快。" },
    { id: "steady-rise", label: "稳步增长", params: { a1: 1, factor: 1.2, offset: 1, count: 8 }, note: "乘数接近 1 时，递推也可能是稳步增长，不一定一下子拉得很开。" },
    { id: "flat", label: "接近稳定", params: { a1: 3, factor: 0.8, offset: 1, count: 8 }, note: "当乘数小于 1 时，递推可能慢慢靠近某个稳定区间。" },
    { id: "fall", label: "逐步下降", params: { a1: 4, factor: 0.7, offset: -0.5, count: 8 }, note: "如果乘数和常数项共同作用向下，数列就会出现递减趋势。" },
  ],
  viewport: { xMin: 0, xMax: 10, yMin: -5, yMax: 25 },
  features: { animation: true, gridToggle: true, keyPointToggle: true, explanationCards: true },
  initialMessage: "准备好了，先固定首项，只看递推乘数和常数项怎样改变后面的项。",
  liveMessage: "递推数列最该看的不是最终公式，而是每一项到底是怎么从前一项长出来的。",
  resetMessage: "已经回到最基础的递推数列模型。",
};
