export const config = {
  id: "physics-uniform-motion-demo",
  title: "匀速直线运动演示器",
  eyebrow: "物理运动学 · 匀速直线运动",
  heroText: "把位移、速度、时间和图像放回同一张图里，让孩子直接看到“斜率为什么就是速度”。",
  graphTitle: "位移-时间图像",
  graphNote: "横轴是时间 t，纵轴是位置 s。先盯住图像斜率，再回头看速度数值。",
  controlHint: "推荐按 v → s0 → t 的顺序观察",
  sampleHint: "先看 4 组典型运动情境",
  teachingHint: "先把图像读懂，再回头记公式",
  backHref: "../../modules/unit-physics-uniform-motion.html",
  backLabel: "返回匀速直线运动单元",
  controls: [
    { key: "v", label: "速度 v", type: "range", min: -3, max: 4, step: 0.2, default: 2 },
    { key: "s0", label: "初始位置 s0", type: "range", min: -5, max: 5, step: 0.5, default: 1 },
    { key: "t", label: "观察时刻 t", type: "range", min: 0, max: 8, step: 0.2, default: 3 },
  ],
  presets: [
    { id: "forward", label: "稳定前进", params: { v: 2, s0: 1, t: 3 }, note: "速度保持不变，图像就是一条稳定上升的直线。" },
    { id: "from-origin", label: "从原点出发", params: { v: 1.5, s0: 0, t: 4 }, note: "初始位置在原点时，图像会从 (0,0) 出发。" },
    { id: "reverse", label: "反向运动", params: { v: -1.6, s0: 4, t: 3 }, note: "速度是负的，图像会向右下方倾斜，说明位置在持续减小。" },
    { id: "same-speed-shift", label: "只改起点", params: { v: 2, s0: -3, t: 3 }, note: "速度不变时，改 s0 只会整体平移直线，不会改变斜率。" },
  ],
  viewport: { xMin: 0, xMax: 8, yMin: -8, yMax: 8 },
  features: { animation: true, gridToggle: true, keyPointToggle: true, explanationCards: true },
  initialMessage: "准备好了，先固定一个时刻，只改速度 v，看图像斜率怎样变化。",
  liveMessage: "先看直线是往上还是往下，再看它有多陡，这就是速度方向和大小。",
  resetMessage: "已经回到最基础的匀速运动模型。",
};
