export const config = {
  id: "set-operations-demo",
  title: "集合运算与韦恩图演示器",
  eyebrow: "集合与逻辑 · 交并补",
  heroText: "先看哪一块区域被高亮，再去理解交集、并集和补集的正式写法。",
  graphTitle: "韦恩图舞台",
  graphNote: "先看区域含义，再读结果集合。",
  controlTitle: "运算切换",
  controlHint: "补集一定先看全集",
  sampleTitle: "典型样例",
  sampleHint: "切换不同重叠场景",
  teachingTitle: "当前提示",
  teachingHint: "图像和结果集合要同步看",
  backHref: "../../modules/unit-set-operations.html",
  backLabel: "返回集合运算与韦恩图单元",
  controls: [
    {
      key: "mode",
      label: "表达模式",
      type: "select",
      default: "life",
      options: [
        { value: "life", label: "生活化" },
        { value: "math", label: "数学化" },
      ],
    },
    {
      key: "sampleId",
      label: "样例",
      type: "select",
      default: "hobbies-overlap",
      options: [
        { value: "hobbies-overlap", label: "兴趣爱好重叠" },
        { value: "numbers-overlap", label: "数字集合重叠" },
      ],
    },
    {
      key: "operation",
      label: "运算",
      type: "select",
      default: "intersection",
      options: [
        { value: "intersection", label: "交集" },
        { value: "union", label: "并集" },
        { value: "complementA", label: "A 的补集" },
      ],
    },
    {
      key: "focusKey",
      label: "当前重点",
      type: "select",
      default: "intersection",
      options: [
        { value: "intersection", label: "共同部分" },
        { value: "union", label: "全部合起来" },
        { value: "complement", label: "补集" },
        { value: "universe", label: "全集" },
      ],
    },
  ],
  presets: [
    {
      id: "intersect",
      label: "先看交集",
      params: { mode: "life", sampleId: "hobbies-overlap", operation: "intersection", focusKey: "intersection" },
      note: "交集只取同时属于 A 和 B 的共同部分。",
    },
    {
      id: "union",
      label: "再看并集",
      params: { mode: "math", sampleId: "numbers-overlap", operation: "union", focusKey: "union" },
      note: "并集不是只看重叠，而是两边出现过的都要收进去。",
    },
    {
      id: "complement",
      label: "最后看补集",
      params: { mode: "math", sampleId: "numbers-overlap", operation: "complementA", focusKey: "complement" },
      note: "补集一定要先盯住全集，再去掉属于 A 的部分。",
    },
  ],
  viewport: { xMin: -8, xMax: 8, yMin: -6, yMax: 6 },
  features: { animation: false, gridToggle: false, keyPointToggle: false, explanationCards: true },
  initialMessage: "准备好了，先从交集开始看区域关系。",
  liveMessage: "继续切换交、并、补，把区域和结果集合对应起来。",
  resetMessage: "已经回到集合运算演示器的默认样例。",
};
