export const config = {
  id: "chemistry-dispersion-colloid-demo",
  title: "分散系与胶体演示器",
  eyebrow: "化学语言与表征 · 分散系",
  heroText: "把溶液、胶体、浊液放进同一个观察窗口里，让孩子同时看到粒子尺度、均一性和光束表现为什么会不同。",
  graphTitle: "粒子与光路观察舞台",
  graphNote: "先切换分散系类型，再打开或关闭入射光束，观察光路、沉降趋势和过滤结论怎样一起变化。",
  controlTitle: "观察条件",
  controlHint: "先切换体系，再看光束表现",
  sampleTitle: "典型样例",
  sampleHint: "从真溶液到浊液按层次比较",
  teachingTitle: "观察提示",
  teachingHint: "盯住“粒子尺度”这条主线",
  backHref: "../../modules/unit-chemistry-dispersion-colloid.html",
  backLabel: "返回分散系与胶体单元",
  controls: [
    {
      key: "systemType",
      label: "分散系类型",
      type: "select",
      default: "colloid",
      options: [
        { value: "solution", label: "溶液" },
        { value: "colloid", label: "胶体" },
        { value: "suspension", label: "浊液" },
      ],
    },
    {
      key: "beamOn",
      label: "打开入射光束",
      type: "toggle",
      default: true,
    },
  ],
  presets: [
    {
      id: "solution",
      label: "真溶液对照",
      params: { systemType: "solution", beamOn: true },
      note: "粒子最小、分布最均匀，光路通常不明显。",
    },
    {
      id: "colloid",
      label: "胶体观察",
      params: { systemType: "colloid", beamOn: true },
      note: "胶体的关键不是“会不会溶”，而是粒子尺度正好能让光路显现出来。",
    },
    {
      id: "suspension",
      label: "浊液对照",
      params: { systemType: "suspension", beamOn: true },
      note: "浊液粒子更大，更容易沉降，也更容易被过滤分离。",
    },
    {
      id: "beam-off",
      label: "关灯再看",
      params: { systemType: "colloid", beamOn: false },
      note: "先看到“像一样混着”，再打开光束，丁达尔效应会更有对比感。",
    },
  ],
  viewport: { xMin: -1, xMax: 13, yMin: -1, yMax: 9 },
  features: { animation: true, gridToggle: false, keyPointToggle: false, explanationCards: true },
  initialMessage: "先把三类分散系都切一遍，再问孩子：真正决定现象差别的，是哪一个微观变量？",
  liveMessage: "别只记现象名称，始终把“粒子大小”与“光路表现”连在一起。",
  resetMessage: "已经回到最基础的胶体观察场景。",
};
