export const config = {
  id: "exp-log-demo",
  title: "指数与对数演示器",
  eyebrow: "函数主线 · 指数与对数",
  heroText: "把底数、增长快慢和互逆关系放到同一张图里看清楚。",
  graphTitle: "双曲线舞台",
  graphNote: "先看底数在 1 的哪一侧，再看增减趋势。",
  controlHint: "底数不能取 1",
  sampleHint: "先看增长，再看衰减",
  teachingHint: "指数函数和对数函数要成对看",
  controls: [
    { key: "base", label: "底数 a", type: "range", min: 0.3, max: 3, step: 0.05, default: 2 },
  ],
  presets: [
    { id: "growth", label: "标准增长", params: { base: 2 }, note: "先看 a > 1 的情形，指数和对数都会随着 x 增大而增大。" },
    { id: "fast", label: "增长更快", params: { base: 3 }, note: "底数更大以后，指数函数会抬头更快，对数函数会更平。" },
    { id: "slow", label: "缓慢增长", params: { base: 1.4 }, note: "当底数只比 1 大一点时，指数增长会明显变慢。" },
    { id: "decay", label: "指数衰减", params: { base: 0.5 }, note: "当 0 < a < 1 时，指数函数会衰减，对数函数也会下降。" },
  ],
  viewport: { xMin: -4, xMax: 6, yMin: -5, yMax: 6 },
  features: { animation: true, gridToggle: true, keyPointToggle: true, explanationCards: true },
  initialMessage: "先看 a 在 1 的哪一侧，再判断指数和对数的趋势。",
  liveMessage: "指数函数和对数函数不是两块孤立内容，它们是一对互逆函数。",
  resetMessage: "已经回到最标准的底数 a = 2。",
};
