export const config = {
  id: "physics-connected-bodies-demo",
  title: "连接体受力演示器",
  eyebrow: "物理受力分析 · 连接体整体隔离",
  heroText: "把两个相连物体、外力、张力和整体加速度放到同一张图里，让孩子看见整体法和隔离法为什么要配合使用。",
  graphTitle: "连接体受力图",
  graphNote: "红色是外力，绿色是连接处张力，蓝色是系统加速度。先看整体，再回头看局部，会比一上来就拆开稳很多。",
  controlHint: "推荐按 外力 → 两个质量 → 观察整体与局部结果 的顺序观察",
  sampleHint: "先看 4 种典型连接体情境",
  teachingHint: "先整体求 a，再局部求 T",
  backHref: "../../modules/unit-physics-connected-bodies.html",
  backLabel: "返回连接体受力单元",
  controls: [
    { key: "m1", label: "前物体质量 m1", type: "range", min: 1, max: 6, step: 0.1, default: 2 },
    { key: "m2", label: "后物体质量 m2", type: "range", min: 1, max: 6, step: 0.1, default: 3 },
    { key: "f", label: "外力 F", type: "range", min: 2, max: 30, step: 0.5, default: 20 },
  ],
  presets: [
    { id: "balanced", label: "基础情境", params: { m1: 2, m2: 3, f: 20 }, note: "先整体求加速度，再隔离后面的物体求张力，是最标准的连接体起步模型。" },
    { id: "heavier-rear", label: "后块更重", params: { m1: 2, m2: 5, f: 20 }, note: "后面的物体更重时，同样外力下整体加速度会变小，但连接处张力仍要承担拉动后块的任务。" },
    { id: "heavier-front", label: "前块更重", params: { m1: 5, m2: 2, f: 20 }, note: "前块更重时，整体仍一起加速，但局部张力分配会和上一种场景不同。" },
    { id: "larger-force", label: "外力更大", params: { m1: 2, m2: 3, f: 28 }, note: "外力增大时，加速度和连接处张力都会一起上升。" },
  ],
  viewport: { xMin: 0, xMax: 12, yMin: 0, yMax: 6 },
  features: { animation: true, gridToggle: false, keyPointToggle: true, explanationCards: true },
  initialMessage: "准备好了，先固定质量，只改外力，看整体加速度和张力怎样一起变。",
  liveMessage: "连接体题里，先整体再隔离，通常会比直接拆两块一起列式更稳。",
  resetMessage: "已经回到最基础的连接体场景。",
};
