export const config = {
  id: "english-sentence-structure-demo",
  title: "句子成分演示器",
  eyebrow: "英语语法 · 句子结构",
  heroText: "把主谓宾、定状补和从句修饰关系拆成结构图，让孩子先看见句子骨架，再回头理解语法术语和阅读过程。",
  graphTitle: "句子结构观察舞台",
  graphNote: "先锁定句子主干，再看修饰成分依附在哪个节点上，最后再追问：这个成分到底在句子里起什么作用？",
  controlTitle: "句子切换",
  controlHint: "先找主干，再找修饰",
  sampleTitle: "典型样例",
  sampleHint: "先看简单句，再看带从句修饰的句子",
  teachingTitle: "观察提示",
  teachingHint: "每次先说谁是主干",
  backHref: "../../modules/unit-english-sentence-structure.html",
  backLabel: "返回句子成分结构拆解单元",
  controls: [
    {
      key: "sentenceId",
      label: "当前句型",
      type: "select",
      default: "simple-main",
      options: [
        { value: "simple-main", label: "简单主干句" },
        { value: "relative-clause", label: "定语从句句型" },
      ],
    },
    {
      key: "focusNodeId",
      label: "聚焦成分",
      type: "select",
      default: "predicate",
      options: [
        { value: "predicate", label: "谓语" },
        { value: "subject", label: "主语" },
        { value: "object", label: "宾语" },
        { value: "relative", label: "从句/修饰" },
        { value: "adverbial", label: "状语" },
      ],
    },
  ],
  presets: [
    { id: "main", label: "先看主干", params: { sentenceId: "simple-main", focusNodeId: "predicate" }, note: "最适合先建立“主语 + 谓语 + 宾语”这一条最基础的阅读骨架。" },
    { id: "modifier", label: "再看修饰", params: { sentenceId: "simple-main", focusNodeId: "adverbial" }, note: "让孩子看见状语不是额外装饰，而是在修饰动作怎样发生。" },
    { id: "clause", label: "从句依附", params: { sentenceId: "relative-clause", focusNodeId: "relative" }, note: "从句场景最适合建立“修饰关系依附在名词上”的层级感。" },
  ],
  viewport: { xMin: 0, xMax: 12, yMin: 0, yMax: 8 },
  features: { animation: true, gridToggle: false, keyPointToggle: false, explanationCards: true },
  initialMessage: "先让孩子回答一句话里谁是主干，谁是在补充说明。",
  liveMessage: "只要主干先看清，复杂句也会变得容易拆。",
  resetMessage: "已经回到最基础的简单主干句。",
};
