export const config = {
  id: "set-basics-demo",
  title: "集合基础概念演示器",
  eyebrow: "集合与逻辑 · 基础概念",
  heroText: "先看对象怎样进入集合框，再去理解属于、不属于、子集、真子集和空集。",
  graphTitle: "集合舞台",
  graphNote: "先看框选关系，再回头读集合符号。",
  controlTitle: "概念切换",
  controlHint: "一次只盯住一个概念",
  sampleTitle: "典型样例",
  sampleHint: "像老师换板书一样切换",
  teachingTitle: "当前提示",
  teachingHint: "把符号翻回图像语言",
  backHref: "../../modules/unit-sets-basics.html",
  backLabel: "返回集合基础概念单元",
  controls: [
    {
      key: "mode",
      label: "表达模式",
      type: "select",
      default: "life",
      options: [
        { value: "life", label: "生活化" },
        { value: "math", label: "数学化" },
      ],
    },
    {
      key: "sampleId",
      label: "样例",
      type: "select",
      default: "shapes-basic",
      options: [
        { value: "shapes-basic", label: "颜色与图形" },
        { value: "numbers-basic", label: "自然数分类" },
        { value: "letters-basic", label: "字母归类" },
      ],
    },
    {
      key: "focusKey",
      label: "当前重点",
      type: "select",
      default: "belong",
      options: [
        { value: "belong", label: "属于" },
        { value: "notBelong", label: "不属于" },
        { value: "subset", label: "子集" },
        { value: "properSubset", label: "真子集" },
        { value: "emptySet", label: "空集" },
      ],
    },
  ],
  presets: [
    {
      id: "life-belong",
      label: "先看属于",
      params: { mode: "life", sampleId: "shapes-basic", focusKey: "belong" },
      note: "先确认对象有没有被装进 A，再写属于符号。",
    },
    {
      id: "math-proper",
      label: "再看真子集",
      params: { mode: "math", sampleId: "numbers-basic", focusKey: "properSubset" },
      note: "真子集比子集多一步：两个集合不能完全相同。",
    },
    {
      id: "math-empty",
      label: "最后看空集",
      params: { mode: "math", sampleId: "letters-basic", focusKey: "emptySet" },
      note: "空集没有元素，但它依然是一个集合。",
    },
  ],
  viewport: { xMin: -8, xMax: 8, yMin: -6, yMax: 7 },
  features: { animation: false, gridToggle: false, keyPointToggle: false, explanationCards: true },
  initialMessage: "准备好了，先看对象怎样进入集合框。",
  liveMessage: "继续切换概念，把图上的关系和集合符号对应起来。",
  resetMessage: "已经回到集合基础概念的默认样例。",
};
