export const config = {
  id: "physics-mechanical-energy-demo",
  title: "机械能守恒演示器",
  eyebrow: "物理功与能量 · 机械能守恒",
  heroText: "把高度变化、势能变化和动能补偿放进同一张能量图里，让孩子看见“守恒”究竟守的是什么。",
  graphTitle: "高度与能量条图",
  graphNote: "左边是当前位置高度，右边是势能、动能和总机械能。关键观察点是：势能在降，动能在补，但总量不变。",
  controlHint: "推荐按 当前高度 → 初始高度 → 质量 → 重力加速度 的顺序观察",
  sampleHint: "先看 4 种典型守恒场景",
  teachingHint: "先说出哪一部分能量在减少，哪一部分在增加",
  backHref: "../../modules/unit-physics-mechanical-energy.html",
  backLabel: "返回机械能守恒单元",
  controls: [
    { key: "m", label: "质量 m", type: "range", min: 1, max: 5, step: 0.1, default: 2 },
    { key: "g", label: "重力加速度 g", type: "range", min: 8, max: 12, step: 0.1, default: 10 },
    { key: "h0", label: "初始高度 h0", type: "range", min: 4, max: 20, step: 0.5, default: 10 },
    { key: "h", label: "当前高度 h", type: "range", min: 0, max: 20, step: 0.5, default: 6 },
  ],
  presets: [
    { id: "high-start", label: "高处出发", params: { m: 2, g: 10, h0: 12, h: 10 }, note: "刚开始下落时，势能仍占大头，动能刚开始增加。" },
    { id: "midway", label: "中途转化", params: { m: 2, g: 10, h0: 12, h: 6 }, note: "下降到一半左右时，势能已经明显转给动能，但总机械能并没有变。" },
    { id: "near-bottom", label: "接近底部", params: { m: 2, g: 10, h0: 12, h: 1 }, note: "接近最低点时，势能很小，绝大多数机械能都已经转成动能。" },
    { id: "larger-mass", label: "质量更大", params: { m: 4, g: 10, h0: 12, h: 6 }, note: "质量变大后，势能、动能和总机械能都会一起放大，但守恒关系本身不变。" },
  ],
  viewport: { xMin: -1, xMax: 9, yMin: -0.2, yMax: 1.3 },
  features: { animation: true, gridToggle: false, keyPointToggle: true, explanationCards: true },
  initialMessage: "准备好了，先只改当前高度，看势能减少多少、动能就补上多少。",
  liveMessage: "机械能守恒里最值得先盯住的是：势能和动能在变，但总机械能不变。",
  resetMessage: "已经回到最基础的机械能守恒场景。",
};
