export const config = {
  id: "english-writing-paragraph-workshop-demo",
  title: "段落展开工坊演示器",
  eyebrow: "英语写作 · 段落展开",
  heroText: "把一段话怎样从主题句长成完整段落拆成结构图，让孩子不再只是堆句子。",
  graphTitle: "段落展开观察舞台",
  graphNote: "先确定这一段最想表达什么，再补支撑句、例子句和收束句，不要一上来就堆信息。",
  controlTitle: "段落样例切换",
  controlHint: "先定主题，再分层展开",
  sampleTitle: "典型样例",
  sampleHint: "先看观点段，再看问题解决段",
  teachingTitle: "观察提示",
  teachingHint: "每次先说这一段最核心的一句",
  backHref: "../../modules/unit-english-writing-paragraph-workshop.html",
  backLabel: "返回作文段落展开工坊单元",
  controls: [
    {
      key: "paragraphId",
      label: "当前段落",
      type: "select",
      default: "opinion-paragraph",
      options: [
        { value: "opinion-paragraph", label: "观点段" },
        { value: "problem-solution", label: "问题解决段" },
      ],
    },
    {
      key: "focusNodeId",
      label: "聚焦层",
      type: "select",
      default: "support-1",
      options: [
        { value: "topic", label: "主题句 / 问题句" },
        { value: "support-1", label: "支撑句 1" },
        { value: "support-2", label: "支撑句 2" },
        { value: "cause", label: "原因句" },
        { value: "solution", label: "办法句" },
        { value: "example", label: "例子句" },
        { value: "detail", label: "补充细节" },
        { value: "closing", label: "收束句" },
      ],
    },
  ],
  presets: [
    { id: "opinion", label: "观点段", params: { paragraphId: "opinion-paragraph", focusNodeId: "support-1" }, note: "最适合先让孩子看见一段话不是一个句子，而是围着主题句逐层展开。" },
    { id: "problem", label: "问题解决段", params: { paragraphId: "problem-solution", focusNodeId: "solution" }, note: "帮助孩子把段落写作从“问题一句带过”推进到“问题 + 原因 + 办法”。" },
  ],
  viewport: { xMin: 0, xMax: 12, yMin: 0, yMax: 8 },
  features: { animation: true, gridToggle: false, keyPointToggle: false, explanationCards: true },
  initialMessage: "先让孩子回答：这段话最核心的一句到底是哪一句？",
  liveMessage: "段落展开越有层级，作文就越不容易只剩句子堆积。",
  resetMessage: "已经回到观点段样例。",
};
