export const config = {
  id: "chemistry-material-classification-demo",
  title: "物质分类演示器",
  eyebrow: "化学语言与定量基础 · 物质分类",
  heroText: "把纯净物、混合物、单质、化合物、酸碱盐重新变成可追踪的分类链，让孩子先知道“眼前这个对象是什么”。",
  graphTitle: "物质分类结构图",
  graphNote: "左边先看具体样例，右边顺着分类路径往上走，再回到底部看它还可能连到哪些典型转化。",
  controlTitle: "样例切换",
  controlHint: "先认对象，再认类别",
  sampleTitle: "典型样例",
  sampleHint: "先看盐，再看单质和混合物",
  teachingTitle: "观察提示",
  teachingHint: "分类和转化要一起看",
  backHref: "../../modules/unit-chemistry-material-classification.html",
  backLabel: "返回物质分类单元",
  controls: [
    {
      key: "sampleId",
      label: "当前样例",
      type: "select",
      default: "sodium-carbonate",
      options: [
        { value: "sodium-carbonate", label: "Na2CO3" },
        { value: "oxygen", label: "O2" },
        { value: "air", label: "空气" },
      ],
    },
  ],
  presets: [
    { id: "salt", label: "盐类样例", params: { sampleId: "sodium-carbonate" }, note: "最适合先建立“纯净物-化合物-盐”这条主链。" },
    { id: "element", label: "单质样例", params: { sampleId: "oxygen" }, note: "切到单质后，孩子会更容易看出分类不是只有酸碱盐。" },
    { id: "mixture", label: "混合物样例", params: { sampleId: "air" }, note: "混合物样例适合补上“先分离，再谈性质”这一层意识。" },
  ],
  viewport: { xMin: 0, xMax: 12, yMin: 0, yMax: 8 },
  features: { animation: true, gridToggle: false, keyPointToggle: false, explanationCards: true },
  initialMessage: "先让孩子回答：这个对象到底是什么，再去谈它能怎么反应。",
  liveMessage: "分类不是死背表格，而是给每一个化学对象先找到位置。",
  resetMessage: "已经回到盐类样例。",
};
