export const config = {
  id: "english-tense-timeline-demo",
  title: "时态时间轴演示器",
  eyebrow: "英语语法 · 时态时间轴",
  heroText: "把时态放回一条时间轴，让孩子看清动作发生点、持续段和当前关注点到底在哪里。",
  graphTitle: "时态时间观察舞台",
  graphNote: "先不要背名称，先问这个时态在时间轴上到底把注意力放在过去、过程还是现在结果。",
  controlTitle: "时态切换",
  controlHint: "先看时间位置，再记时态名称",
  sampleTitle: "典型样例",
  sampleHint: "先看现在完成时，再看过去进行时",
  teachingTitle: "观察提示",
  teachingHint: "每次先说动作在时间轴哪里",
  backHref: "../../modules/unit-english-tense-timeline.html",
  backLabel: "返回语法时态时间轴单元",
  controls: [
    {
      key: "tenseId",
      label: "当前时态",
      type: "select",
      default: "present-perfect",
      options: [
        { value: "present-perfect", label: "现在完成时" },
        { value: "past-continuous", label: "过去进行时" },
      ],
    },
    {
      key: "focusPoint",
      label: "聚焦点",
      type: "select",
      default: "now-result",
      options: [
        { value: "past-start", label: "过去起点" },
        { value: "action", label: "动作节点" },
        { value: "now-result", label: "现在结果" },
        { value: "duration", label: "持续影响" },
        { value: "past-point", label: "过去观察点" },
        { value: "ongoing", label: "进行状态" },
      ],
    },
  ],
  presets: [
    { id: "perfect", label: "现在完成时", params: { tenseId: "present-perfect", focusPoint: "now-result" }, note: "最适合先建立“过去动作 + 现在结果”的直觉。" },
    { id: "continuous", label: "过去进行时", params: { tenseId: "past-continuous", focusPoint: "ongoing" }, note: "帮助孩子看懂过去某一时刻切进去时动作还在进行。" },
  ],
  viewport: { xMin: 0, xMax: 12, yMin: 0, yMax: 8 },
  features: { animation: true, gridToggle: false, keyPointToggle: false, explanationCards: true },
  initialMessage: "先问自己：这个时态把注意力放在动作发生时，还是放在现在结果上？",
  liveMessage: "时态越能放回时间轴，规则记忆就越稳。",
  resetMessage: "已经回到现在完成时样例。",
};
