export const config = {
  id: "chemistry-ionic-reaction-demo",
  title: "离子反应与电解质演示器",
  eyebrow: "化学反应原理 · 离子反应",
  heroText: "把“写方程式”重新拉回溶液粒子层面，帮助孩子分清哪些离子真正反应，哪些只是旁观。",
  graphTitle: "离子反应粒子舞台",
  graphNote: "左侧看真正参与反应的离子，右侧看旁观离子，中下方看生成物，建立“反应实质”视角。",
  controlTitle: "反应情境",
  controlHint: "先换场景，再说谁在反应",
  sampleTitle: "典型样例",
  sampleHint: "先看沉淀，再看中和和气体",
  teachingTitle: "观察提示",
  teachingHint: "每次先说“删掉谁不行”",
  backHref: "../../modules/unit-chemistry-ionic-reaction.html",
  backLabel: "返回离子反应与电解质单元",
  controls: [
    {
      key: "sceneId",
      label: "反应场景",
      type: "select",
      default: "barium-sulfate",
      options: [
        { value: "barium-sulfate", label: "沉淀生成" },
        { value: "acid-base", label: "酸碱中和" },
        { value: "carbonate-acid", label: "酸与碳酸盐" },
      ],
    },
    {
      key: "beamOn",
      label: "高亮混合路径",
      type: "toggle",
      default: true,
    },
  ],
  presets: [
    {
      id: "precipitate",
      label: "沉淀反应",
      params: { sceneId: "barium-sulfate", beamOn: true },
      note: "先抓真正离开溶液的那对离子，再看旁观离子为什么可以约掉。",
    },
    {
      id: "neutralization",
      label: "酸碱中和",
      params: { sceneId: "acid-base", beamOn: true },
      note: "H+ 与 OH- 的结合是酸碱中和最需要看到的核心过程。",
    },
    {
      id: "gas",
      label: "气体生成",
      params: { sceneId: "carbonate-acid", beamOn: true },
      note: "碳酸根遇酸的题，最好让孩子把“先成酸再分解”说出来。",
    },
  ],
  viewport: { xMin: 0, xMax: 12, yMin: 0, yMax: 8 },
  features: { animation: true, gridToggle: false, keyPointToggle: false, explanationCards: true },
  initialMessage: "先问孩子：如果只能保留真正变化的粒子，这个反应还剩下谁？",
  liveMessage: "离子方程式不是删公式，而是保留真正发生变化的粒子。",
  resetMessage: "已经回到最典型的沉淀生成场景。",
};
