export const config = {
  id: "english-synonym-semantic-map-demo",
  title: "近义词语义坐标演示器",
  eyebrow: "英语词汇 · 近义词语义",
  heroText: "把近义词放进语气、时间、力度和对象差异的坐标里，让孩子看清它们为什么像，但又不能随便互换。",
  graphTitle: "近义词语义坐标舞台",
  graphNote: "先抓共同核心义，再看哪个更快、哪个更强、哪个更正式，近义词辨析就会轻松很多。",
  controlTitle: "词组切换",
  controlHint: "先抓共同义，再看语义偏移",
  sampleTitle: "典型样例",
  sampleHint: "先看 look 组，再看 say 组",
  teachingTitle: "观察提示",
  teachingHint: "每次先说共同义，再说不同点",
  backHref: "../../modules/unit-english-synonym-semantic-map.html",
  backLabel: "返回近义词语义坐标图单元",
  controls: [
    {
      key: "groupId",
      label: "当前词组",
      type: "select",
      default: "look",
      options: [
        { value: "look", label: "look 近义组" },
        { value: "say", label: "say 近义组" },
      ],
    },
    {
      key: "focusWord",
      label: "聚焦单词",
      type: "select",
      default: "glance",
      options: [
        { value: "look", label: "look / say" },
        { value: "glance", label: "glance" },
        { value: "watch", label: "watch" },
        { value: "stare", label: "stare" },
        { value: "speak", label: "speak" },
        { value: "tell", label: "tell" },
        { value: "shout", label: "shout" },
      ],
    },
  ],
  presets: [
    { id: "look", label: "look 词组", params: { groupId: "look", focusWord: "glance" }, note: "最适合先让孩子看见“看”这一组词在时间和力度上的差异。" },
    { id: "say", label: "say 词组", params: { groupId: "say", focusWord: "tell" }, note: "帮助孩子看懂“说”这一组词在对象和正式度上的不同。" },
  ],
  viewport: { xMin: 0, xMax: 12, yMin: 0, yMax: 8 },
  features: { animation: true, gridToggle: false, keyPointToggle: false, explanationCards: true },
  initialMessage: "先让孩子回答：这组词共同都在表达什么动作或意思？",
  liveMessage: "近义词最关键的不是中文一样，而是语义位置不一样。",
  resetMessage: "已经回到 look 近义组。",
};
