export const config = {
  id: "english-logic-connector-map-demo",
  title: "逻辑连接词网络演示器",
  eyebrow: "英语词汇 · 逻辑连接",
  heroText: "把转折、因果等高频连接词放进同一张逻辑网络，让孩子先抓关系，再选单词。",
  graphTitle: "逻辑连接观察舞台",
  graphNote: "做阅读和完形时，先判断这里需要转折、因果还是让步，再看具体连接词。",
  controlTitle: "逻辑组切换",
  controlHint: "先看逻辑，再看用词",
  sampleTitle: "典型样例",
  sampleHint: "先看转折组，再看因果组",
  teachingTitle: "观察提示",
  teachingHint: "每次先判断关系类型",
  backHref: "../../modules/unit-english-logic-connector-map.html",
  backLabel: "返回逻辑连接词网络单元",
  controls: [
    {
      key: "groupId",
      label: "当前逻辑组",
      type: "select",
      default: "contrast",
      options: [
        { value: "contrast", label: "转折逻辑" },
        { value: "cause", label: "因果逻辑" },
      ],
    },
    {
      key: "focusConnector",
      label: "聚焦连接词",
      type: "select",
      default: "however",
      options: [
        { value: "however", label: "however" },
        { value: "but", label: "but" },
        { value: "although", label: "although" },
        { value: "instead", label: "instead" },
        { value: "because", label: "because" },
        { value: "so", label: "so" },
        { value: "therefore", label: "therefore" },
        { value: "as-result", label: "as a result" },
      ],
    },
  ],
  presets: [
    { id: "contrast", label: "转折组", params: { groupId: "contrast", focusConnector: "however" }, note: "最适合先让孩子看见基础转折、书面转折和让步转折的分工。" },
    { id: "cause", label: "因果组", params: { groupId: "cause", focusConnector: "therefore" }, note: "帮助孩子分清原因表达和结果表达的方向差异。" },
  ],
  viewport: { xMin: 0, xMax: 12, yMin: 0, yMax: 8 },
  features: { animation: true, gridToggle: false, keyPointToggle: false, explanationCards: true },
  initialMessage: "先让孩子回答：这里最需要表达的是转折、因果，还是别的逻辑关系？",
  liveMessage: "连接词不是替换词库，而是逻辑关系的标签。",
  resetMessage: "已经回到转折逻辑组。",
};
