export const config = {
  id: "sin-basic-demo",
  title: "sin 函数演示器",
  eyebrow: "三角函数 · sin(x) 基础",
  heroText: "把角度、函数值和标准正弦曲线连在一起看，让波形不再抽象。",
  graphTitle: "正弦图像舞台",
  graphNote: "先盯住 0、π/2、π、3π/2、2π 这五个关键位置。",
  controlHint: "拖动当前角度，观察点在曲线上怎么走",
  sampleHint: "五个关键角一键切换",
  teachingHint: "先看象限，再看符号",
  controls: [
    { key: "angle", label: "当前角", type: "range", min: 0, max: 6.283185307179586, step: 0.05, default: 0 },
  ],
  presets: [
    { id: "start", label: "0", params: { angle: 0 }, note: "从 0 开始，正弦值也从 0 出发。" },
    { id: "peak", label: "π/2", params: { angle: Math.PI / 2 }, note: "到 π/2 时，正弦值达到最大值 1。" },
    { id: "zero", label: "π", params: { angle: Math.PI }, note: "到 π 时，正弦值回到 0。" },
    { id: "trough", label: "3π/2", params: { angle: (3 * Math.PI) / 2 }, note: "到 3π/2 时，正弦值达到最小值 -1。" },
    { id: "end", label: "2π", params: { angle: Math.PI * 2 }, note: "到 2π 时，一个完整周期结束。" },
  ],
  viewport: { xMin: 0, xMax: Math.PI * 2, yMin: -1.6, yMax: 1.6 },
  features: { animation: true, gridToggle: true, keyPointToggle: true, explanationCards: true },
  initialMessage: "先看五个关键角，再拖动中间位置补全波形感觉。",
  liveMessage: "正弦函数最重要的是先把关键角的位置看熟。",
  resetMessage: "已经回到正弦曲线的起点。",
};
