export const config = {
  id: "chemistry-chlorine-demo",
  title: "氯及其化合物演示器",
  eyebrow: "元素化合物 · 氯",
  heroText: "把氯气、盐酸、次氯酸、漂白液串成一条现象与微观变化同步展开的链路，帮助孩子看懂漂白主角究竟是谁。",
  graphTitle: "含氯物质转化链",
  graphNote: "先看当前场景，再抓“谁是漂白主角”，最后把性质、用途和安全提醒连回整条链。",
  controlTitle: "场景切换",
  controlHint: "先找活性物质，再讲用途",
  sampleTitle: "典型样例",
  sampleHint: "先看氯水，再看漂白，再回到氯气本体",
  teachingTitle: "观察提示",
  teachingHint: "漂白主角一定要说清",
  backHref: "../../modules/unit-chemistry-chlorine.html",
  backLabel: "返回氯及其化合物单元",
  controls: [
    {
      key: "sceneId",
      label: "当前场景",
      type: "select",
      default: "chlorine-water",
      options: [
        { value: "chlorine-hydrogen", label: "氯气与氢气" },
        { value: "chlorine-water", label: "氯水形成" },
        { value: "bleach", label: "漂白液作用" },
      ],
    },
  ],
  presets: [
    { id: "chlorine-water", label: "氯水主线", params: { sceneId: "chlorine-water" }, note: "最适合讲“漂白不是 Cl2 本身”的关键误区。" },
    { id: "bleach", label: "漂白液主线", params: { sceneId: "bleach" }, note: "把家庭经验和课堂知识连起来，理解会更牢。" },
    { id: "hydrogen", label: "氯气本体", params: { sceneId: "chlorine-hydrogen" }, note: "回到氯气强氧化性的原点，再看后面链路会更清晰。" },
  ],
  viewport: { xMin: 0, xMax: 12, yMin: 0, yMax: 8 },
  features: { animation: true, gridToggle: false, keyPointToggle: false, explanationCards: true },
  initialMessage: "先问孩子：真正起漂白作用的是 Cl2、HCl，还是 HClO？",
  liveMessage: "氯这一章最关键的不是死记用途，而是看清哪一种含氯物质在真正发挥作用。",
  resetMessage: "已经回到氯水形成的基础场景。",
};
