export const config = {
  id: "english-affix-network-demo",
  title: "前后缀网络演示器",
  eyebrow: "英语词汇 · 前后缀网络",
  heroText: "把词缀、词根和派生词放进一张组合图，让孩子看清单词怎样因为前后缀变化而改变方向、词性和用法。",
  graphTitle: "前后缀组合舞台",
  graphNote: "先抓词根核心义，再看前缀把方向怎么拉走、后缀把词性怎么变出来，单词就会开始从“点”变成“网”。",
  controlTitle: "词族切换",
  controlHint: "先看词缀作用，再看派生结果",
  sampleTitle: "典型样例",
  sampleHint: "先看 re-view，再看 impossible 类否定前缀",
  teachingTitle: "观察提示",
  teachingHint: "每次先拆构件，再看整词",
  backHref: "../../modules/unit-english-affix-network.html",
  backLabel: "返回前后缀变义网络单元",
  controls: [
    {
      key: "familyId",
      label: "当前词族",
      type: "select",
      default: "re-view",
      options: [
        { value: "re-view", label: "re- + view" },
        { value: "im-possible", label: "im- + possible" },
      ],
    },
    {
      key: "emphasis",
      label: "讲解重点",
      type: "select",
      default: "prefix",
      options: [
        { value: "prefix", label: "前缀作用" },
        { value: "suffix", label: "后缀/词性" },
      ],
    },
  ],
  presets: [
    { id: "review", label: "review 词族", params: { familyId: "re-view", emphasis: "prefix" }, note: "最适合先让孩子看见前缀怎样改变动作方向。" },
    { id: "impossible", label: "否定前缀", params: { familyId: "im-possible", emphasis: "prefix" }, note: "否定前缀很适合建立“意义翻转”的直觉。" },
  ],
  viewport: { xMin: 0, xMax: 12, yMin: 0, yMax: 8 },
  features: { animation: true, gridToggle: false, keyPointToggle: false, explanationCards: true },
  initialMessage: "先让孩子回答：这个词如果去掉词缀，还剩下什么核心义？",
  liveMessage: "词根给核心义，词缀给方向和变化，单词就不再只是拼写块。",
  resetMessage: "已经回到 re-view 词族。",
};
