export const config = {
  id: "chemistry-redox-demo",
  title: "氧化还原反应演示器",
  eyebrow: "化学反应原理 · 氧化还原",
  heroText: "把化合价变化、电子转移、氧化剂和还原剂四条线放到一个画面里，帮助孩子真正看懂“谁失谁得”。",
  graphTitle: "电子转移观察舞台",
  graphNote: "左边看失电子的一方，右边看得电子的一方，中间箭头表示电子转移，底部再对应化合价变化。",
  controlTitle: "反应条件",
  controlHint: "先认谁失电子、谁得电子",
  sampleTitle: "典型样例",
  sampleHint: "先看 Fe2+/Cl2，再看更生活化的 CuO + H2",
  teachingTitle: "观察提示",
  teachingHint: "电子和化合价必须同时讲",
  backHref: "../../modules/unit-chemistry-redox.html",
  backLabel: "返回氧化还原反应与电子转移单元",
  controls: [
    {
      key: "reactionId",
      label: "反应样例",
      type: "select",
      default: "iron-oxidation",
      options: [
        { value: "iron-oxidation", label: "Fe2+ 与 Cl2" },
        { value: "copper-hydrogen", label: "CuO 与 H2" },
      ],
    },
    {
      key: "electronView",
      label: "电子显示方式",
      type: "select",
      default: "balanced",
      options: [
        { value: "balanced", label: "总量平衡" },
        { value: "step", label: "分步提示" },
      ],
    },
  ],
  presets: [
    {
      id: "iron",
      label: "Fe2+ 被氧化",
      params: { reactionId: "iron-oxidation", electronView: "balanced" },
      note: "非常适合讲“失电子就是被氧化，得电子就是被还原”。",
    },
    {
      id: "iron-step",
      label: "分步看电子",
      params: { reactionId: "iron-oxidation", electronView: "step" },
      note: "先让孩子说出电子去哪儿，再回到化合价变化。",
    },
    {
      id: "copper",
      label: "氧化铜与氢气",
      params: { reactionId: "copper-hydrogen", electronView: "balanced" },
      note: "这个样例能把得氧失氧、电子转移和化合价变化连到一起。",
    },
  ],
  viewport: { xMin: 0, xMax: 12, yMin: 0, yMax: 8 },
  features: { animation: true, gridToggle: false, keyPointToggle: false, explanationCards: true },
  initialMessage: "先固定一个反应，让孩子只回答一件事：电子从谁那里出发，最后到了谁那里？",
  liveMessage: "氧化还原反应里，化合价变化只是电子转移的另一种写法。",
  resetMessage: "已经回到 Fe2+ 与 Cl2 的基础观察场景。",
};
