export const config = {
  id: "english-sentence-compression-demo",
  title: "长难句压缩演示器",
  eyebrow: "英语阅读 · 长难句压缩",
  heroText: "把长句先压回主干，再把让步、条件、时间和超长主语这些附着层一层层挂回去，让孩子真正掌握拆长难句的步骤。",
  graphTitle: "长难句压缩舞台",
  graphNote: "每次先只保留主干，再看哪些部分只是背景、条件或补充，阅读负担会明显下降。",
  controlTitle: "句型切换",
  controlHint: "先保主干，再回挂附着层",
  sampleTitle: "典型样例",
  sampleHint: "先看让步长句，再看超长主语句",
  teachingTitle: "观察提示",
  teachingHint: "不要一口气全读，先压缩后展开",
  backHref: "../../modules/unit-english-sentence-compression.html",
  backLabel: "返回长难句主干压缩单元",
  controls: [
    {
      key: "sentenceId",
      label: "当前句型",
      type: "select",
      default: "although-researchers",
      options: [
        { value: "although-researchers", label: "让步 + 条件长句" },
        { value: "whoever-practices", label: "超长主语句" },
      ],
    },
    {
      key: "focusLayer",
      label: "聚焦层",
      type: "select",
      default: "main-trunk",
      options: [
        { value: "main-trunk", label: "主干" },
        { value: "concession", label: "让步背景" },
        { value: "condition", label: "条件补充" },
        { value: "subject-block", label: "主语块" },
      ],
    },
  ],
  presets: [
    { id: "trunk", label: "先抓主干", params: { sentenceId: "although-researchers", focusLayer: "main-trunk" }, note: "最适合先建立“压缩长句先找主干”的动作意识。" },
    { id: "subject", label: "超长主语", params: { sentenceId: "whoever-practices", focusLayer: "subject-block" }, note: "帮助孩子看懂主语很长时也要先整体打包。" },
  ],
  viewport: { xMin: 0, xMax: 12, yMin: 0, yMax: 8 },
  features: { animation: true, gridToggle: false, keyPointToggle: false, explanationCards: true },
  initialMessage: "先问自己：这句话就算只剩骨架，最想表达的主干动作是什么？",
  liveMessage: "长难句不是全读不懂，而是还没有先把主干保住。",
  resetMessage: "已经回到让步 + 条件长句样例。",
};
