export const config = {
  id: "line-conic-relation-demo",
  title: "直线与圆锥曲线位置关系演示器",
  eyebrow: "解析几何 · 综合理解",
  heroText: "用一条可上下移动的水平直线，统一观察它与抛物线、椭圆、双曲线的相离、相切、相交变化。",
  graphTitle: "位置关系变化舞台",
  graphNote: "先看直线在哪，再看公共点个数，最后回到方程结构。",
  controlHint: "先切曲线类型，再拖动水平直线",
  sampleHint: "三类曲线的典型位置一键切换",
  teachingHint: "先数公共点，再判断关系",
  backHref: "../../modules/analytic-geometry.html",
  backLabel: "返回解析几何模块",
  controls: [
    {
      key: "family",
      label: "曲线类型",
      type: "select",
      default: "parabola",
      options: [
        { value: "parabola", label: "抛物线" },
        { value: "ellipse", label: "椭圆" },
        { value: "hyperbola", label: "双曲线" },
      ],
    },
    { key: "lineY", label: "水平直线 y", type: "range", min: -6, max: 6, step: 0.2, default: 0 },
    { key: "a", label: "主参数 a", type: "range", min: 2, max: 6, step: 0.2, default: 4 },
    { key: "b", label: "辅助参数 b", type: "range", min: 1.5, max: 4.5, step: 0.1, default: 3 },
  ],
  presets: [
    { id: "parabola-tangent", label: "抛物线相切", params: { family: "parabola", lineY: 0, a: 2.5, b: 3 }, note: "水平直线经过抛物线顶点时，只会碰到一次。" },
    { id: "parabola-secant", label: "抛物线相交", params: { family: "parabola", lineY: 2, a: 2.5, b: 3 }, note: "水平直线进入抛物线开口内部后，会出现两个公共点。" },
    { id: "ellipse-tangent", label: "椭圆相切", params: { family: "ellipse", lineY: 3, a: 5, b: 3 }, note: "水平直线碰到椭圆最高点或最低点时，只有一个公共点。" },
    { id: "hyperbola-secant", label: "双曲线相交", params: { family: "hyperbola", lineY: 5, a: 4, b: 3 }, note: "水平直线高于双曲线顶点后，会切到左右两支。" },
  ],
  viewport: { xMin: -10, xMax: 10, yMin: -8, yMax: 8 },
  features: { animation: true, gridToggle: true, keyPointToggle: true, explanationCards: true },
  initialMessage: "准备好了，先切换曲线类型，再观察水平直线怎样改变公共点个数。",
  liveMessage: "做位置关系题时，先别急着算，先看直线经过的是曲线外部、边界还是内部。",
  resetMessage: "已经回到直线与圆锥曲线位置关系的基础状态。",
};
